# Prep: BigBird fine-tuning for long news articles

Fine-tunes `ilos-vigil/bigbird-small-indonesian-nli` (max length 512) with the Hugging Face `Trainer` and weighted F1.

In [ ]:
DATA_DIR = "../data"

In [2]:
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '0'

## Import Library

In [3]:
!pip install -q evaluate datasets transformers

In [4]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu115

In [6]:
import pandas as pd
import numpy as np

from transformers import AutoTokenizer, TFAutoModelForSequenceClassification, TFBertModel, TFAutoModel, \
    TrainingArguments, Trainer, AutoModelForSequenceClassification, EarlyStoppingCallback, BigBirdModel
import evaluate, torch
import tensorflow as tf
import keras.backend as K
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.initializers import TruncatedNormal
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.metrics import CategoricalAccuracy
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Input, Dense

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, recall_score, precision_score

In [7]:
df = pd.read_csv(f"{DATA_DIR}/gemastik_22.csv")
df.head()

,id,sumber,kodekat,kodesubkat,kategori,subkategori,katakunci,tanggal,judul_berita,konten_berita,nama_tokoh,jabatan,organisasi,lokasi,alias,kutipan,sentimen_kutipan,sentimen_berita
0,568576e9e95,Detik,Q,Q,Jasa Kesehatan dan Kegiatan Sosial Swasta,Jasa Kesehatan dan Kegiatan Sosial Swasta,Jumlah pasien,2021-06-17,"BOR Sudah 89 Persen, RSUD Soreang Bandung Siap...",Bandung -\n\nSatuan Tugas Penanganan COVID-19 ...,[],['Bupati Bandung'],"['Bed Occupancy Ratio (BOR)', 'Pemda', 'BOR']","['Bandung', 'Kabupaten Bandung', 'Kota Bandung']",[],"['mengatakan, telah mengadakan rapat dan memut...",Netral,Netral
1,80f931fe95e,Detik,D,D2,Pengadaan Listrik dan Gas,Pengadaan Gas dan Produksi Es,Jaringan Gas,2021-03-18,"Honda CB650R Indonesia Dapat Penyegaran, Harga...",Jakarta -\n\nAstra Honda Motor (AHM) resmi men...,"['Biasa Mejeng', 'Resmi Dijual']",[],"['Big', 'LED']","['Jakarta', 'Indonesia']",[],"['""Rasa bangga itu menyempurnakan gaya hidup m...",Positif,Positif
2,1bd2af6ef23,Antara,C,C8,Industri Pengolahan,"Industri Kimia, Farmasi dan Obat Tradisional",farmasi,2021-02-23,Vaksin COVID-19 Pfizer disetujui satu dari tig...,Seoul (ANTARA) - Panel ahli pertama dari tiga ...,['Mulyo Sunyoto'],[],"['Universitas Oxford', 'BioNTech']","['Korea Selatan', 'Amerika Serikat', 'Korsel',...",['¬©'],[],Netral,Positif
3,ac2b55af24c,Detik,A,A2,"Pertanian, Kehutanan, dan Perikanan",Kehutanan dan Penebangan Kayu,bambu,2021-01-26,"TPU Srengseng Sawah Penuh, DKI Rujuk Jenazah C...","Jakarta - TPU Srengseng Sawah, Jakarta Selatan...",['Ivan Nurcahyo'],[],"['Pemprov DKI', 'Dinas Pertamanan']","['Jakarta', 'Jakarta Selatan', 'DKI Jakarta', ...",[],"['""Kita sebutnya TPU Bambu Wulung, sebenarnya ...",Positif,Positif
4,3f50747a1d4,Antara,Q,Q,Jasa Kesehatan dan Kegiatan Sosial Swasta,Jasa Kesehatan dan Kegiatan Sosial Swasta,wabah penyakit,2021-05-04,Media Korea Utara sebut vaksin COVID-19 bukan ...,Seoul (ANTARA) - Media pemerintah Korea Utara ...,['Edwin Salvador'],[],['Partai Buruh'],"['Korea Utara', 'Korea Selatan', 'China', 'Kor...",['¬©'],['mengatakan wabah di sana tidak dapat dikesam...,Netral,Netral

In [8]:
df['judul_konten'] = df['judul_berita'] + ' ' + df['konten_berita']
df['judul_konten'].head()

0    BOR Sudah 89 Persen, RSUD Soreang Bandung Siap...
1    Honda CB650R Indonesia Dapat Penyegaran, Harga...
2    Vaksin COVID-19 Pfizer disetujui satu dari tig...
3    TPU Srengseng Sawah Penuh, DKI Rujuk Jenazah C...
4    Media Korea Utara sebut vaksin COVID-19 bukan ...
Name: judul_konten, dtype: object

In [9]:
# MODEL = 'cardiffnlp/twitter-roberta-base-sentiment-latest'
# MODEL = 'ayameRushia/bert-base-indonesian-1.5G-sentiment-analysis-smsa'
MODEL = 'ilos-vigil/bigbird-small-indonesian-nli'

In [10]:
df['judul_konten'].tolist()[:5]

['BOR Sudah 89 Persen, RSUD Soreang Bandung Siapkan 100 Kasur Bandung -\n\nSatuan Tugas Penanganan COVID-19 Kabupaten Bandung memutuskan akan menggunakan RSUD Soreang menjadi lokasi penanganan pasien COVID-19. Sebanyak 100 kasur akan disiapkan di RSUD Soreang.\n\nSebelumnya, Kabupaten Bandung masuk dalam zona risiko tinggi atau zona merah. Per tanggal 16 Juni 2021, Bed Occupancy Ratio (BOR) atau keterisian ruang isolasi mencapai 89 persen.\n\nHal tersebut diungkapkan oleh Bupati Bandung Dadang Supriatna. Ia mengatakan, telah mengadakan rapat dan memutuskan untuk menggunakan RSUD Soreang dijadikan rumah sakit rujukan bagi pasien COVID-19.\n\n"Kita sudah instruksikan dan rapat evaluasi untuk bed, karena RSUD Soreang lama sudah ada pemindahan dan ijin sudah hampir selesai. Maka kami sudah sepakat akan menambah 100 bed isolasi dalam membantu masyarakat," ujar Bupati Bandung Dadang Supriatna, di Komplek Pemda Bandung, Kamis (1762021).\n\nSelain di RSUD Soreang, sejumlah rumah sakit rujukan COVID-19 di Kabupaten Bandung pun menambah ketersediaan kasur untuk pasien COVID. Di antaranya, RSUD Cicalengka, RSUD Majalaya dan RSUD Al-Ihsan.\n\n"Di RS Soreang lama itu di kasih 100 bed, RS Cicalengkankurang lebih 20 bed, Majalaya 20 bed, dan Al Ihsan 36 bed," ujar Dadang.\n\nBaca juga: Simulasi PTM Kota Bandung Dihentikan Imbas Kenaikan Kasus Corona\n\nLanjut Dadang, ditambahkan jumlah kasur isolasi itu dimaksudkan untuk mengantisipasi terjadinya lonjakan kasus pasien positif COVID. Ditambahnya kasur isolasi pun diharapkan mampu menurunkan angka BOR di Kabupaten Bandung.\n\n"Kalau misalkan ini terus bertambah maka BOR nya akan turun ke 40 persen," katanya.\n\nSementara itu, apabila jumlah kasur tersebut tidak juga cukup akan ada kemungkinan alternatif lain. Di mana pihaknya menyiapkan Stadion Jalak Harupat menjadi lokasi isolasi.\n\n"Kalau sekarang kan kebutuhan itu sekitar 150 bed, nah kalaunini belum mencukupi maka akan membuka kemungkinan Jalak Harupat jadi ruang isolasi," pungkasnya.\n\n(mudmud)\n\nbandung\nbirojabar\nrsud soreang\nbor\nlonjakan kasus corona',
 'Honda CB650R Indonesia Dapat Penyegaran, Harga Rp 296,4 Juta Jakarta -\n\nAstra Honda Motor (AHM) resmi menghadirkan Honda CB650R 2021. Sepeda motor sport berkonsep Neo Sport Caf√© ini tampil makin gagah, dengan warna dan sentuhan baru.\n\nHonda CB650R diperkenalkan pertama kali pada awal 2019. Setelah lebih dari dua tahun, akhirnya AHM memberi penyegaran pada model ini. CB650R 2021 kini mempunyai warna hitam doff (Matte Gunpowder Black Metallic). Penyegaran terbaru ini menemani pilihan warna merah (Candy Chromosphere Red).\n\nKomposisi warna baru ini disematkan pada sepatbor depan (front fender) dan tangki bahan bakar. Pada model terbaru CB650R, desain sepatbor belakang (rear fender) menggunakan unsur logam yang semakin kuat.\n\nBaca juga: Dear AHM, New CB190SS Cocok Banget Lho Buat Pengganti Honda Tiger\n\n"Rasa bangga itu menyempurnakan gaya hidup masa kini untuk para penggemar sepeda motor sport premium. Tentunya kami (AHM) akan terus konsisten memberikan layanan khusus yang memanjakan pengguna big bike Honda melalui jaringan dealer Big Wing kami yang tersebar di berbagai kota," ujar Marketing Director AHM Thomas Wijaya, dalam keterangan resminya, Kamis (1832021).\n\nDesain\n\nHonda CB650R menganut desain timeless (tak lekang oleh waktu) dan menekankan pada ciri khas motor street fighter. Sepintas pada sosoknya hadir kesan sporty, modern, sekaligus ekstrem.\n\nMotor ini memiliki lampu depan LED bulat, dengan penyematan all LED lighting system dan lensa bening pada lampu senja, di lampu belakang, lampu sein.\n\nMenguatkan kesan modern, motor ini juga didukung tampilan full digital panelmeter dengan pencahayaan berwarna biru berisi informasi posisi gir, dan shift up indicator. Juga ada informasi putaran mesin, kecepatan, odometer, bahan bakar, rata-rata konsumsi bahan bakar, serta penunjuk waktu.\n\nBaca juga: Intip Spesifikasi Motor Marc Marquez Rp 7 Miliaran yang Biasa Mejeng di Sentul\n\nFitur\n\nSoal fitur, Honda CB650R 2021 menggunakan suspensi depan inverted telescopic Showa 41mm, suspensi belakang tunggal dengan lengan ayun alumunium. Bagian ini memiliki pengaturan hingga 10 level disesuaikan dengan kebutuhan pengendara.\n\nFitur assistslipper clutch yang disematkan, membuat tuas kopling menjadi lebih ringan dioperasikan, sekaligus bisa mengurangi efek engine brake ketika melakukan penurunan gigi dengan cepat.\n\nHonda Selectable Torque Control (HSTC) menjadi peranti wajib untuk Honda CB650R, yang bertugas menyesuaikan tenaga mesin demi mengoptimalkan torsi pada roda belakang dan mengurangi selip. Penyematan Emergency Stop Signal (ESS) pada Honda CB650R menunjang keselamatan saat dilakukan pengereman mendadak.\n\nESS secara otomatis mengaktifkan lampu darurat (hazard) saat rem dioperasikan, sehingga dapat memberi peringatan kepada pengendara di sekitarnya, terutama pada kendaraan di belakang untuk menghindari kemungkinan kecelakaan.\n\nBaca juga: Emak-emak Tukang Sayur Naik CBR Ngebut 100 KmJam\n\nPerforma Mesin dan Pendukungnya\n\nHonda CB650R 2021 dibekali mesin 4 silinder 650cc DOHC, 6-percepatan, yang mampu menghasilkan tenaga puncak 66,5kW @11.000 rpm dan torsi kuat 60,7Nm @8.000 rpm. Kapasitas tangki bahan bakar tercatat 15,4 liter, dan spesifikasi mesin sudah memenuhi standar emisi yang ditetapkan pemerintah.\n\nModel knalpot pada Honda CB650R ini memiliki desain compact namun kokoh, sehingga menambah kesan maskulin dan diklaim memberi performa optimal pada putaran mesin bawah-tengah. Sekaligus, komponen lubang gas buang sisa pembakaran ini mampu menghasilkan suara yang khas.\n\nBig bike 650 cc ini memiliki rangka diamond steel yang kokoh berbentuk elips. Keseimbangan kekuatan didapatkan melalui penyetelan secara khusus yang lebih kaku di sekitar headstock dan lebih fleksibel di sisi spar, sehingga memberikan karakter pengendalian yang diinginkan pengendara.\n\nPosisi berkendara agak condong ke bagian depan, menempatkan pengendara dekat dengan roda depan. Jok pembonceng memberikan ruang yang cukup didukung dengan tali untuk keamanan. Profil jok pengendara yang pas membantu jangkauan kaki ke tanah, dengan ketinggian tempat duduk 810mm.\n\nPelek aluminium dibalut ban depan berukuran 12070-R17, serta ban belakang ukuran 18055-R17. Model ini menggunakan kaliper rem depan berpiston empat dengan cakram 310mm. Di bagian belakang tersemat kaliper berpiston tunggal dengan cakram 240mm, yang menghasilkan daya pengereman berlimpah dengan ABS 2-channel sebagai peranti standar.\n\nHonda CB650R dipasarkan dalam dua warna, Matte Gunpowder Black Metallic dan Candy Chromosphere Red, dibanderol Rp 296.400.000 on the road wilayah Jakarta.\n\nSimak Video "Honda City Hatcback RS Resmi Dijual di Indonesia"\n\n[Gambas:Video 20detik]\n\n(luadin)\n\nhonda\nastra honda motor\nhonda cb650r',
 'Vaksin COVID-19 Pfizer disetujui satu dari tiga panel ahli di Korsel Seoul (ANTARA) - Panel ahli pertama dari tiga kelompok pakar di Korea Selatan yang meninjau vaksin COVID-19 yang dikembangkan oleh Pfizer Inc dan BioNTech memberikan rekomendasi pada Selasa agar pemerintah menyetujui vaksin tersebut.\n\nPanel farmasi nasional itu berencana untuk membuat rekomendasinya pada Jumat (262), hari yang sama ketika Korea Selatan akan memulai program imunisasi. Tapi, pemerintah akan menunggu panel ketiga, yang belum mengatakan kapan akan mencapai kesimpulan, sebelum memutuskan apakah akan memberikan persetujuan.\n\nIndividu berisiko tinggi, yang diprioritaskan pada awal kampanye vaksinasi, akan disuntik dengan vaksin yang dikembangkan oleh AstraZeneca dan Universitas Oxford.\n\nNamun, sehari kemudian, Korea Selatan akan menggunakan 117.000 dosis vaksin PfizerBioNTech yang telah dipasok melalui COVAX, program berbagi vaksin virus corona internasional, tanpa perlu persetujuan akhir pemerintah.\n\nSekitar 55.000 petugas kesehatan di fasilitas perawatan COVID-19 akan menerima dosis pertama vaksin PfizerBioNTech pada Sabtu (272).\n\nPanel pertama yang melaporkan vaksin Pfizer  BioNTech menyarankan bahwa vaksin itu harus diberikan kepada orang-orang yang berusia 16 tahun ke atas, dengan mempertimbangkan hasil uji coba global dan persetujuannya di beberapa negara lain.\n\nPfizer telah berjanji untuk menggandakan pasokan vaksinnya untuk Amerika Serikat pada pertengahan Maret dan meningkatkan ekspektasi produksi global untuk 2021 menjadi setidaknya dua miliar dosis.\n\nKorea Selatan melaporkan 357 kasus baru virus corona pada Senin (222). Jumlah total infeksi sekarang mencapai 87.681, dengan jumlah kematian 1.573.\n\nSumber: Reuters\n\nBaca juga: Dokter di Korsel ancam unjuk rasa, vaksinasi COVID bisa terganggu\n\nBaca juga: Korea Selatan akan mulai gunakan vaksin Pfizer pada 27 Februari\n\nBaca juga: PM Korea Selatan jamin keamanan vaksin AstraZeneca\n\nBandung siapkan sanksi bagi warga penolak vaksin\n\nPenerjemah: Mulyo Sunyoto\nEditor: Tia Mutiasari\nCOPYRIGHT ¬© ANTARA 2021',
 'TPU Srengseng Sawah Penuh, DKI Rujuk Jenazah COVID-19 ke TPU Bambu Wulung Jakarta - TPU Srengseng Sawah, Jakarta Selatan, yang semula dikhususkan untuk pemakaman jenazah pasien COVID-19 sudah penuh. Pemprov DKI Jakarta kini membuka TPU Bambu Wulung yang berada di Jakarta Timur.\n\n"Kita sebutnya TPU Bambu Wulung, sebenarnya dia lokasi satu hamparan sama Bambu Apus, cuma memang aksesnya berbeda dan memang itu di persiapkan untuk TPU yang berbeda, tapi menyatu dengan Bambu Apus lah memang. Iya Bambu Wulung khusus muslim. Muslim kan masih kita buka dua lokasi, tapi kemarin siang sudah kita tutup di Srengseng Sawah," ujar Kapusdatin Dinas Pertamanan dan Hutan Kota DKI Jakarta Ivan Nurcahyo kepada wartawan, Selasa (2612021).\n\nBaca juga: Ini Lokasi Tambahan Makam Baru Jenazah COVID-19 di DKI Jakarta\n\nIvan menerangkan total ada 800 petak makam yang disiapkan khusus untuk COVID-19. Ke-800 petak itu berada di area seluas 3.000 meter.\n\n"Kapasitas petak makamnya 800 petak makam. Kalau untuk area sekitar 3.000 meter yang sudah siap," ucapnya.\n\nIvan mengatakan sejak Senin (251) sudah ada 162 jenazah muslim yang dimakamkan di TPU Bambu Wulung menggunakan protokol COVID-19. Sementara jenazah nonmuslim dimakamkan di TPU Tegal Alur.\n\n"Iya Bambu Wulung semua yang muslimnya. Yang untuk Kristen kita kirim ke Tegal Alur. Tapi yang lokasi lokasi lain itu terima, tapi untuk tumpang," katanya.\n\nBaca juga: Pemprov DKI Beli 5 Lahan untuk Pemakaman Jenazah Pasien COVID-19\n\nTercatat, ada empat TPU baru yang disiapkan Pemprov DKI khusus untuk pemakaman COVID-19. TPU Pertama yakni Srengseng Sawah dan kini sudah penuh.\n\n"Sampai saat ini yang kita siapkan 4 lokasi. Yang pertama itu Srengseng Sawah itu 5.000 meter persegi yang kita tutup. Udah terus 560 petak. Per tanggal 25 kan kita tutup kemarin ya," katanya.\n\nKemudian ada TPU Bambu Wulung, yang ketiga ada TPU Tegal Alur yang berada di Jalan Sahabat, Jakarta Barat. Terakhir ada TPU Rorotan yang masih dalam persiapan.\n\n(manmae)\n\ntpu\njenazah covid-19\ntpu srengseng sawah\npemprov dki',
 'Media Korea Utara sebut vaksin COVID-19 bukan obat mujarab Seoul (ANTARA) - Media pemerintah Korea Utara pada Selasa memperingatkan kemungkinan pertempuran panjang melawan virus corona, dan mengatakan vaksin yang dikembangkan oleh perusahaan obat global terbukti "bukan obat mujarab universal".\n\nNegara itu belum secara resmi mengonfirmasi adanya infeksi, meskipun para pejabat Korea Selatan mengatakan wabah di sana tidak dapat dikesampingkan, karena Korea Utara memiliki hubungan perdagangan dan antarmasyarakat dengan China, sebelum menutup perbatasannya awal tahun lalu.\n\nRodong Sinmun, surat kabar resmi Partai Buruh yang berkuasa, mengatakan pandemi malah memburuk, meskipun vaksin sudah dikembangkan.\n\nVaksin anti virus corona baru yang diperkenalkan secara kompetitif oleh berbagai negara pernah dianggap sebagai secercah harapan bagi umat manusia karena dianggap dapat mengakhiri perang melawan penyakit menakutkan ini, sebut media itu.\n\n"Tetapi situasi di banyak negara dengan jelas membuktikan bahwa vaksin tidak pernah menjadi obat mujarab universal," kata surat kabar tersebut, yang mengutip laporan berita tentang meningkatnya jumlah kasus baru di luar negeri dan masalah keamanan.\n\nSurat kabar Korea Utara itu mendesak orang-orang untuk bersiap menghadapi pandemi yang berkepanjangan, menggambarkannya sebagai "kenyataan tak terhindarkan" yang memerlukan upaya untuk memperkuat langkah-langkah anti virus serta menumbuhkan loyalitas kepada pemimpin Kim Jong Un dan partainya.\n\nKorea Utara berharap menerima hampir dua juta dosis vaksin COVID-19 AstraZeneca pada paruh pertama tahun ini, melalui program berbagi vaksin global COVAX.\n\nNamun, perwakilan Organisasi Kesehatan Dunia (WHO) untuk Korea Utara Edwin Salvador mengatakan pada April bahwa pengiriman vaksin ditunda karena kekurangan pasokan, mengutip Aliansi Vaksin GAVI.\n\nDalam komentarnya kepada Reuters, Salvador mengatakan Korea Utara sedang menyelesaikan persyaratan teknis yang diperlukan untuk menerima vaksin. Ia tidak menjelaskan lebih lanjut.\n\nSumber: Reuters\n\nBaca juga: Intelijen Korsel sebut Korut coba mencuri teknologi vaksin Pfizer\n\nBaca juga: Korea Utara peringatkan AS untuk hentikan permainan perang\n\nBaca juga: Malaysia sesalkan pemutusan hubungan diplomatik Korea Utara\n\nMerayakan ultah pendiri Korea Utara dengan pesta dansa\n\nPenerjemah: Yashinta Difa Pramudyani\nEditor: Tia Mutiasari\nCOPYRIGHT ¬© ANTARA 2021']

In [11]:
LABEL_MAP = {
    "Negatif": 0,
    "Netral": 1,
    "Positif": 2,
}

INV_LABEL_MAP = {v: k for k, v in LABEL_MAP.items()}

X = df['judul_konten'].values
y = np.array(df["sentimen_berita"].map(LABEL_MAP))
print(X.shape, y.shape)
y[:10]

(5289,) (5289,)

array([1, 2, 2, 2, 1, 1, 2, 1, 2, 2])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4231,), (1058,), (4231,), (1058,))

In [13]:
tokenizer = AutoTokenizer.from_pretrained(MODEL)

In [14]:
MAX_LENGTH = 512

tokenized_text_detail_train = tokenizer(
    text=X_train.tolist(),
    add_special_tokens=True,
    max_length=MAX_LENGTH,
    truncation=True,
    padding=True,
    return_tensors='pt',
    return_token_type_ids=False,
    return_attention_mask=True,
    verbose=True
)

tokenized_text_detail_test = tokenizer(
    text=X_test.tolist(),
    add_special_tokens=True,
    max_length=MAX_LENGTH,
    truncation=True,
    padding=True,
    return_tensors='pt',
    return_token_type_ids=False,
    return_attention_mask=True,
    verbose=True
)

tokenized_text_detail_train

{'input_ids': tensor([[    3,   605,  4518,  ..., 12272,   173,     4],
        [    3,   180,  3871,  ...,   751,   692,     4],
        [    3,  1951,  1321,  ..., 18160,   619,     4],
        ...,
        [    3,  1345,   147,  ...,     0,     0,     0],
        [    3,  8539,    85,  ...,   500,  1951,     4],
        [    3, 15161,  1292,  ...,  1525,   144,     4]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]])}

In [15]:
token_ids_train = np.array(tokenized_text_detail_train["input_ids"])
token_masks_train = np.array(tokenized_text_detail_train["attention_mask"])
token_ids_test = np.array(tokenized_text_detail_test["input_ids"])
token_masks_test = np.array(tokenized_text_detail_test["attention_mask"])

token_ids_train.shape, token_masks_train.shape, token_ids_test.shape, token_masks_test.shape

((4231, 512), (4231, 512), (1058, 512), (1058, 512))

## Using Trainer

In [16]:
# Create torch dataset
class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        if self.labels:
            item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.encodings["input_ids"])

In [17]:
train_dataset = Dataset({
    "input_ids": token_ids_train,
    "attention_mask": token_masks_train,
}, y_train.tolist())
test_dataset = Dataset({
    "input_ids": token_ids_test,
    "attention_mask": token_masks_test,
}, y_test.tolist())

In [18]:
bigbird_model = AutoModelForSequenceClassification.from_pretrained(MODEL, num_labels=3)

In [19]:
args = TrainingArguments(
    output_dir="test_trainer",
    evaluation_strategy="steps",
    eval_steps=500,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=10,
    seed=42,
    load_best_model_at_end=True,
)


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return f1_metric.compute(predictions=predictions, references=labels, average="weighted")

f1_metric = evaluate.load("f1", average="weighted")


trainer = Trainer(
    model=bigbird_model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
)

Downloading builder script:   0%|          | 0.00/6.77k [00:00<?, ?B/s]

In [20]:
trainer.train()

Attention type 'block_sparse' is not possible if sequence_length: 512 <= num global tokens: 2 * config.block_size + min. num sliding tokens: 3 * config.block_size + config.num_random_blocks * config.block_size + additional buffer: config.num_random_blocks * config.block_size = 704 with config.block_size = 64, config.num_random_blocks = 3. Changing attention type to 'original_full'...

TrainOutput(global_step=1330, training_loss=0.4209721873577376, metrics={'train_runtime': 128.1357, 'train_samples_per_second': 330.197, 'train_steps_per_second': 10.38, 'total_flos': 1707552336107520.0, 'train_loss': 0.4209721873577376, 'epoch': 10.0})

In [21]:
trainer.evaluate()

{'eval_loss': 0.9220414757728577,
 'eval_f1': 0.6469084468616438,
 'eval_runtime': 0.7996,
 'eval_samples_per_second': 1323.136,
 'eval_steps_per_second': 42.52,
 'epoch': 10.0}

In [22]:
torch.cuda.empty_cache()