# EDA: test set status codes and the single Credential Access sample

Compares status codes between train and test and inspects the lone `Credential Access` row (`POST /wp-login.php`).

In [ ]:
DATA_DIR = "../data"

In [1]:
import pandas as pd

In [2]:
test_df = pd.read_csv(f"{DATA_DIR}/test.csv")

In [3]:
test_df.columns

Index(['id', 'timestamp', 'remote_addr', 'remote_user', 'hostname',
       'time_local', 'request', 'status', 'body_bytes_sent', 'http_referer',
       'http_user_agent', 'http_x_forwarded_for', 'time_iso8601',
       'request_method', 'request_length', 'bytes_sent', 'http_referer2',
       'request_time', 'upstream_connect_time', 'upstream_header_time',
       'upstream_response_time', 'upstream_addr', 'upstream_status',
       'connection', 'connection_requests', 'data.srcip', 'agent.ip'],
      dtype='object')

In [4]:
test_df['status'].value_counts()

404    12722
200      656
400      152
422       25
502       22
500       11
504        6
416        2
403        1
405        1
407        1
Name: status, dtype: int64

In [5]:
train_df = pd.read_csv(f"{DATA_DIR}/train.csv")

In [9]:
train_df['rule.mitre.tactic'].value_counts()

["non-attack"]           52101
["Impact"]                1784
["Reconnaissance"]         561
["Defense Evasion"]         29
["Initial Access"]           4
["Credential Access"]        1
Name: rule.mitre.tactic, dtype: int64

In [13]:
train_df.head(1)

,id,timestamp,remote_addr,remote_user,hostname,time_local,request,status,body_bytes_sent,http_referer,...,upstream_connect_time,upstream_header_time,upstream_response_time,upstream_addr,upstream_status,connection,connection_requests,data.srcip,agent.ip,rule.mitre.tactic
0,0,"Aug 29, 2023 @ 17:00:03.058",114.4.220.184,-,vm-director-nginx,30/Aug/2023:00:00:02 +0700,GET /auth/resources/ofl9o/login/ub/ HTTP/2.0,404,118,-,...,0.001,0.002,0.002,10.45.184.148:32442,404,688306444,2,114.4.220.184,192.168.1.99,"[""non-attack""]"

In [10]:
data = train_df[train_df['rule.mitre.tactic'] == '["Credential Access"]']

In [14]:
data_cek = train_df[train_df['request'] == 'POST /wp-login.php HTTP/1.1']

In [16]:
pd.set_option('display.max_columns', None)

In [17]:
data

,id,timestamp,remote_addr,remote_user,hostname,time_local,request,status,body_bytes_sent,http_referer,http_user_agent,http_x_forwarded_for,time_iso8601,request_method,request_length,bytes_sent,http_referer2,request_time,upstream_connect_time,upstream_header_time,upstream_response_time,upstream_addr,upstream_status,connection,connection_requests,data.srcip,agent.ip,rule.mitre.tactic
22171,22171,"Sep 1, 2023 @ 00:28:08.410",85.215.200.224,-,vm-director-nginx,01/Sep/2023:07:28:07 +0700,POST /wp-login.php HTTP/1.1,200,956,https://admisi.notrealdomain.com/wp-admin/,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,-,2023-09-01T07:28:07+07:00,POST,684,1224,https://admisi.notrealdomain.com/wp-admin/,0.006,0,0.006,0.006,175.45.184.125:80,200,701008974,1,85.215.200.224,192.168.1.99,"[""Credential Access""]"

In [18]:
data_cek

,id,timestamp,remote_addr,remote_user,hostname,time_local,request,status,body_bytes_sent,http_referer,http_user_agent,http_x_forwarded_for,time_iso8601,request_method,request_length,bytes_sent,http_referer2,request_time,upstream_connect_time,upstream_header_time,upstream_response_time,upstream_addr,upstream_status,connection,connection_requests,data.srcip,agent.ip,rule.mitre.tactic
21717,21717,"Sep 1, 2023 @ 00:18:41.964",85.215.200.224,-,vm-director-nginx,01/Sep/2023:07:18:39 +0700,POST /wp-login.php HTTP/1.1,404,47,https://siam.notrealdomain.com/wp-admin/,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,-,2023-09-01T07:18:39+07:00,POST,657,304,https://siam.notrealdomain.com/wp-admin/,0.002,0.001,0.003,0.003,175.45.184.234:80,404,700926127,1,85.215.200.224,192.168.1.99,"[""non-attack""]"
22171,22171,"Sep 1, 2023 @ 00:28:08.410",85.215.200.224,-,vm-director-nginx,01/Sep/2023:07:28:07 +0700,POST /wp-login.php HTTP/1.1,200,956,https://admisi.notrealdomain.com/wp-admin/,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,-,2023-09-01T07:28:07+07:00,POST,684,1224,https://admisi.notrealdomain.com/wp-admin/,0.006,0,0.006,0.006,175.45.184.125:80,200,701008974,1,85.215.200.224,192.168.1.99,"[""Credential Access""]"
22466,22466,"Sep 1, 2023 @ 00:31:10.717",85.215.200.224,-,vm-director-nginx,01/Sep/2023:07:31:09 +0700,POST /wp-login.php HTTP/1.1,404,47,https://siam.notrealdomain.com/wp-admin/,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,-,2023-09-01T07:31:09+07:00,POST,648,304,https://siam.notrealdomain.com/wp-admin/,0.003,0,0.003,0.003,175.45.184.234:80,404,701046170,1,85.215.200.224,192.168.1.99,"[""non-attack""]"
22631,22631,"Sep 1, 2023 @ 00:36:04.987",85.215.200.224,-,vm-director-nginx,01/Sep/2023:07:36:02 +0700,POST /wp-login.php HTTP/1.1,404,47,https://siam.notrealdomain.com/wp-admin/,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,-,2023-09-01T07:36:02+07:00,POST,657,304,https://siam.notrealdomain.com/wp-admin/,0.003,0.001,0.003,0.003,175.45.184.234:80,404,701085872,1,85.215.200.224,192.168.1.99,"[""non-attack""]"
22880,22880,"Sep 1, 2023 @ 00:41:49.396",85.215.200.224,-,vm-director-nginx,01/Sep/2023:07:41:47 +0700,POST /wp-login.php HTTP/1.1,404,47,https://siam.notrealdomain.com/wp-admin/,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,-,2023-09-01T07:41:47+07:00,POST,648,304,https://siam.notrealdomain.com/wp-admin/,0.002,0,0.002,0.002,175.45.184.234:80,404,701137915,1,85.215.200.224,192.168.1.99,"[""non-attack""]"