# BERT / RoBERTa fine-tuning on English-translated tweets: schedulers, Optuna search and contextual augmentation

In [ ]:
DATA_DIR = "../data"

In [2]:
import pandas as pd
train_eng_df = pd.read_csv(f'{DATA_DIR}/train_eng_v2.csv')

In [3]:
train_eng_df.label.value_counts()

label
Politik                    2858
Sosial Budaya               381
Ekonomi                     263
Pertahanan dan Keamanan     255
Ideologi                    253
Sumber Daya Alam            134
Demografi                    55
Geografi                     19
Name: count, dtype: int64

In [1]:
import pandas as pd
from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import train_test_split

# Load the CSV file
file_path = f'{DATA_DIR}/train_eng_v2.csv'
df = pd.read_csv(file_path)

# Create a label mapping
label_mapping = {
    'Politik': 0,
    'Sosial Budaya': 1,
    'Ekonomi': 2,
    'Pertahanan dan Keamanan': 3,
    'Ideologi': 4,
    'Sumber Daya Alam': 5,
    'Demografi': 6,
    'Geografi': 7
}

# Apply the label mapping
df['label'] = df['label'].map(label_mapping)

# Split the DataFrame into training and validation sets
train_df, val_df = train_test_split(df, test_size=0.2, stratify=df['label'], random_state=42)

# Convert DataFrames to Datasets
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

# Combine into a DatasetDict
dataset = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset
})

# Tokenize the dataset
model_name = "cardiffnlp/roberta-large-tweet-topic-single-all"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Load the model
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)

Map:   0%|          | 0/3374 [00:00<?, ? examples/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at cardiffnlp/roberta-large-tweet-topic-single-all and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([6, 1024]) in the checkpoint and torch.Size([8, 1024]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([6]) in the checkpoint and torch.Size([8]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [71]:
# Define training arguments
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=7,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)


# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/2954 [00:00<?, ?it/s]

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 0.8514370918273926, 'eval_runtime': 6.2076, 'eval_samples_per_second': 135.962, 'eval_steps_per_second': 17.076, 'epoch': 1.0}
{'loss': 0.9354, 'grad_norm': 20.451250076293945, 'learning_rate': 1.6635071090047395e-05, 'epoch': 1.18}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 0.8287328481674194, 'eval_runtime': 6.3218, 'eval_samples_per_second': 133.506, 'eval_steps_per_second': 16.767, 'epoch': 2.0}
{'loss': 0.6867, 'grad_norm': 17.444509506225586, 'learning_rate': 1.3249830737982399e-05, 'epoch': 2.37}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 0.9527471661567688, 'eval_runtime': 6.2946, 'eval_samples_per_second': 134.083, 'eval_steps_per_second': 16.84, 'epoch': 3.0}
{'loss': 0.4839, 'grad_norm': 1.8719180822372437, 'learning_rate': 9.878131347325661e-06, 'epoch': 3.55}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.1647626161575317, 'eval_runtime': 6.339, 'eval_samples_per_second': 133.145, 'eval_steps_per_second': 16.722, 'epoch': 4.0}
{'loss': 0.3346, 'grad_norm': 45.36210250854492, 'learning_rate': 6.492890995260665e-06, 'epoch': 4.74}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.4584412574768066, 'eval_runtime': 6.3301, 'eval_samples_per_second': 133.33, 'eval_steps_per_second': 16.745, 'epoch': 5.0}
{'loss': 0.1938, 'grad_norm': 7.139780044555664, 'learning_rate': 3.1144211238997974e-06, 'epoch': 5.92}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.5495885610580444, 'eval_runtime': 6.2687, 'eval_samples_per_second': 134.637, 'eval_steps_per_second': 16.909, 'epoch': 6.0}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.6634888648986816, 'eval_runtime': 6.3301, 'eval_samples_per_second': 133.331, 'eval_steps_per_second': 16.745, 'epoch': 7.0}
{'train_runtime': 998.3059, 'train_samples_per_second': 23.658, 'train_steps_per_second': 2.959, 'train_loss': 0.46432443849929056, 'epoch': 7.0}

  0%|          | 0/106 [00:00<?, ?it/s]

Balanced Accuracy: 0.40651244219830296

In [72]:
# Define training arguments with cosine scheduler
training_args = TrainingArguments(
    output_dir="./cosine",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=1,
    load_best_model_at_end=True,
    learning_rate=2e-5,
    per_device_train_batch_size=8,  # Use a smaller batch size
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    lr_scheduler_type="cosine",  # Use cosine scheduler
    warmup_steps=500,
    logging_dir='./logs',
    logging_steps=10,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)


# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1266 [00:00<?, ?it/s]

{'loss': 0.5433, 'grad_norm': 13.549372673034668, 'learning_rate': 3.6e-07, 'epoch': 0.02}
{'loss': 0.6175, 'grad_norm': 8.441020965576172, 'learning_rate': 7.2e-07, 'epoch': 0.05}
{'loss': 0.3655, 'grad_norm': 10.053191184997559, 'learning_rate': 1.12e-06, 'epoch': 0.07}
{'loss': 0.3727, 'grad_norm': 32.589027404785156, 'learning_rate': 1.52e-06, 'epoch': 0.09}
{'loss': 0.6547, 'grad_norm': 19.343053817749023, 'learning_rate': 1.9200000000000003e-06, 'epoch': 0.12}
{'loss': 0.5346, 'grad_norm': 4.255354881286621, 'learning_rate': 2.3200000000000002e-06, 'epoch': 0.14}
{'loss': 0.5485, 'grad_norm': 48.836002349853516, 'learning_rate': 2.7200000000000002e-06, 'epoch': 0.17}
{'loss': 0.4446, 'grad_norm': 8.987371444702148, 'learning_rate': 3.08e-06, 'epoch': 0.19}
{'loss': 0.4276, 'grad_norm': 23.138946533203125, 'learning_rate': 3.48e-06, 'epoch': 0.21}
{'loss': 0.423, 'grad_norm': 2.7648346424102783, 'learning_rate': 3.88e-06, 'epoch': 0.24}
{'loss': 0.3518, 'grad_norm': 8.923154830932617, 'learning_rate': 4.2800000000000005e-06, 'epoch': 0.26}
{'loss': 0.7616, 'grad_norm': 35.763824462890625, 'learning_rate': 4.680000000000001e-06, 'epoch': 0.28}
{'loss': 0.4552, 'grad_norm': 18.26471710205078, 'learning_rate': 5.0800000000000005e-06, 'epoch': 0.31}
{'loss': 0.6906, 'grad_norm': 7.510412216186523, 'learning_rate': 5.480000000000001e-06, 'epoch': 0.33}
{'loss': 0.4478, 'grad_norm': 8.341060638427734, 'learning_rate': 5.8800000000000005e-06, 'epoch': 0.36}
{'loss': 0.3362, 'grad_norm': 5.986855983734131, 'learning_rate': 6.280000000000001e-06, 'epoch': 0.38}
{'loss': 0.5386, 'grad_norm': 1.3882383108139038, 'learning_rate': 6.680000000000001e-06, 'epoch': 0.4}
{'loss': 0.4432, 'grad_norm': 16.102710723876953, 'learning_rate': 7.04e-06, 'epoch': 0.43}
{'loss': 0.4939, 'grad_norm': 24.98747444152832, 'learning_rate': 7.440000000000001e-06, 'epoch': 0.45}
{'loss': 0.3821, 'grad_norm': 25.73611068725586, 'learning_rate': 7.840000000000001e-06, 'epoch': 0.47}
{'loss': 0.4837, 'grad_norm': 10.254833221435547, 'learning_rate': 8.24e-06, 'epoch': 0.5}
{'loss': 0.4938, 'grad_norm': 10.27110767364502, 'learning_rate': 8.64e-06, 'epoch': 0.52}
{'loss': 0.4224, 'grad_norm': 36.552772521972656, 'learning_rate': 9.040000000000002e-06, 'epoch': 0.55}
{'loss': 0.404, 'grad_norm': 1.4497792720794678, 'learning_rate': 9.440000000000001e-06, 'epoch': 0.57}
{'loss': 0.3786, 'grad_norm': 1.9186989068984985, 'learning_rate': 9.84e-06, 'epoch': 0.59}
{'loss': 0.5209, 'grad_norm': 9.651679039001465, 'learning_rate': 1.024e-05, 'epoch': 0.62}
{'loss': 0.456, 'grad_norm': 0.7672853469848633, 'learning_rate': 1.0640000000000001e-05, 'epoch': 0.64}
{'loss': 0.521, 'grad_norm': 20.619661331176758, 'learning_rate': 1.1040000000000001e-05, 'epoch': 0.66}
{'loss': 0.2366, 'grad_norm': 1.8869768381118774, 'learning_rate': 1.144e-05, 'epoch': 0.69}
{'loss': 0.2248, 'grad_norm': 1.693162441253662, 'learning_rate': 1.184e-05, 'epoch': 0.71}
{'loss': 0.3997, 'grad_norm': 59.16810989379883, 'learning_rate': 1.2240000000000001e-05, 'epoch': 0.73}
{'loss': 0.4653, 'grad_norm': 6.973184585571289, 'learning_rate': 1.2640000000000001e-05, 'epoch': 0.76}
{'loss': 0.6824, 'grad_norm': 16.883901596069336, 'learning_rate': 1.3040000000000002e-05, 'epoch': 0.78}
{'loss': 0.4665, 'grad_norm': 15.151480674743652, 'learning_rate': 1.3440000000000002e-05, 'epoch': 0.81}
{'loss': 0.3711, 'grad_norm': 22.49761962890625, 'learning_rate': 1.384e-05, 'epoch': 0.83}
{'loss': 0.3416, 'grad_norm': 13.874079704284668, 'learning_rate': 1.4240000000000001e-05, 'epoch': 0.85}
{'loss': 0.4621, 'grad_norm': 15.841264724731445, 'learning_rate': 1.464e-05, 'epoch': 0.88}
{'loss': 0.3799, 'grad_norm': 8.184203147888184, 'learning_rate': 1.5040000000000002e-05, 'epoch': 0.9}
{'loss': 0.5715, 'grad_norm': 17.650161743164062, 'learning_rate': 1.544e-05, 'epoch': 0.92}
{'loss': 0.4248, 'grad_norm': 37.6854248046875, 'learning_rate': 1.584e-05, 'epoch': 0.95}
{'loss': 0.4308, 'grad_norm': 16.86602210998535, 'learning_rate': 1.6240000000000004e-05, 'epoch': 0.97}
{'loss': 0.3567, 'grad_norm': 32.20902633666992, 'learning_rate': 1.664e-05, 'epoch': 1.0}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.0251097679138184, 'eval_runtime': 6.2544, 'eval_samples_per_second': 134.945, 'eval_steps_per_second': 16.948, 'epoch': 1.0}
{'loss': 0.2629, 'grad_norm': 40.76283264160156, 'learning_rate': 1.704e-05, 'epoch': 1.02}
{'loss': 0.3723, 'grad_norm': 67.05563354492188, 'learning_rate': 1.7440000000000002e-05, 'epoch': 1.04}
{'loss': 0.5947, 'grad_norm': 33.317386627197266, 'learning_rate': 1.7840000000000002e-05, 'epoch': 1.07}
{'loss': 0.3243, 'grad_norm': 28.078092575073242, 'learning_rate': 1.824e-05, 'epoch': 1.09}
{'loss': 0.4782, 'grad_norm': 5.5779900550842285, 'learning_rate': 1.86e-05, 'epoch': 1.11}
{'loss': 0.4271, 'grad_norm': 29.599376678466797, 'learning_rate': 1.9e-05, 'epoch': 1.14}
{'loss': 0.4461, 'grad_norm': 39.15562057495117, 'learning_rate': 1.94e-05, 'epoch': 1.16}
{'loss': 0.3575, 'grad_norm': 26.252456665039062, 'learning_rate': 1.98e-05, 'epoch': 1.18}
{'loss': 0.759, 'grad_norm': 13.7485990524292, 'learning_rate': 1.9997897495179932e-05, 'epoch': 1.21}
{'loss': 0.3932, 'grad_norm': 29.021827697753906, 'learning_rate': 1.9981082760879432e-05, 'epoch': 1.23}
{'loss': 0.3146, 'grad_norm': 8.467061996459961, 'learning_rate': 1.9947481571753165e-05, 'epoch': 1.26}
{'loss': 0.3681, 'grad_norm': 24.69512939453125, 'learning_rate': 1.989715043918941e-05, 'epoch': 1.28}
{'loss': 0.5681, 'grad_norm': 27.310815811157227, 'learning_rate': 1.9830174011447617e-05, 'epoch': 1.3}
{'loss': 0.2847, 'grad_norm': 0.38635942339897156, 'learning_rate': 1.9746664931294667e-05, 'epoch': 1.33}
{'loss': 0.3076, 'grad_norm': 25.566143035888672, 'learning_rate': 1.9646763646559234e-05, 'epoch': 1.35}
{'loss': 0.5109, 'grad_norm': 40.07009506225586, 'learning_rate': 1.953063817392281e-05, 'epoch': 1.37}
{'loss': 0.4509, 'grad_norm': 12.570117950439453, 'learning_rate': 1.9398483816344728e-05, 'epoch': 1.4}
{'loss': 0.4801, 'grad_norm': 39.999202728271484, 'learning_rate': 1.9250522834596357e-05, 'epoch': 1.42}
{'loss': 0.3504, 'grad_norm': 103.79976654052734, 'learning_rate': 1.9087004073456926e-05, 'epoch': 1.45}
{'loss': 0.3522, 'grad_norm': 20.783153533935547, 'learning_rate': 1.8908202543199646e-05, 'epoch': 1.47}
{'loss': 0.5485, 'grad_norm': 2.3267979621887207, 'learning_rate': 1.8714418957072008e-05, 'epoch': 1.49}
{'loss': 0.4786, 'grad_norm': 10.12419605255127, 'learning_rate': 1.850597922554809e-05, 'epoch': 1.52}
{'loss': 0.2027, 'grad_norm': 51.19401168823242, 'learning_rate': 1.8283233908203547e-05, 'epoch': 1.54}
{'loss': 0.3045, 'grad_norm': 11.01368522644043, 'learning_rate': 1.8046557624134997e-05, 'epoch': 1.56}
{'loss': 0.2831, 'grad_norm': 2.927635669708252, 'learning_rate': 1.7796348421915536e-05, 'epoch': 1.59}
{'loss': 0.2967, 'grad_norm': 33.71316146850586, 'learning_rate': 1.7533027110145857e-05, 'epoch': 1.61}
{'loss': 0.5039, 'grad_norm': 1.0998567342758179, 'learning_rate': 1.7257036549726988e-05, 'epoch': 1.64}
{'loss': 0.1611, 'grad_norm': 1.9676973819732666, 'learning_rate': 1.696884090904484e-05, 'epoch': 1.66}
{'loss': 0.813, 'grad_norm': 170.36294555664062, 'learning_rate': 1.6668924883319288e-05, 'epoch': 1.68}
{'loss': 0.217, 'grad_norm': 4.9355387687683105, 'learning_rate': 1.638939602952576e-05, 'epoch': 1.71}
{'loss': 0.2987, 'grad_norm': 4.197534561157227, 'learning_rate': 1.6068616521763708e-05, 'epoch': 1.73}
{'loss': 0.1437, 'grad_norm': 22.277177810668945, 'learning_rate': 1.5737630650670336e-05, 'epoch': 1.75}
{'loss': 0.3895, 'grad_norm': 0.912587583065033, 'learning_rate': 1.5396995077231856e-05, 'epoch': 1.78}
{'loss': 0.5176, 'grad_norm': 79.63957977294922, 'learning_rate': 1.5047282691564749e-05, 'epoch': 1.8}
{'loss': 0.2403, 'grad_norm': 2.4545392990112305, 'learning_rate': 1.468908164941371e-05, 'epoch': 1.82}
{'loss': 0.5679, 'grad_norm': 16.517602920532227, 'learning_rate': 1.4322994382975386e-05, 'epoch': 1.85}
{'loss': 0.4236, 'grad_norm': 52.3457145690918, 'learning_rate': 1.3949636587711645e-05, 'epoch': 1.87}
{'loss': 0.7015, 'grad_norm': 25.478313446044922, 'learning_rate': 1.3569636186856288e-05, 'epoch': 1.9}
{'loss': 0.103, 'grad_norm': 1.2203373908996582, 'learning_rate': 1.3183632275356777e-05, 'epoch': 1.92}
{'loss': 0.4033, 'grad_norm': 62.35518264770508, 'learning_rate': 1.279227404502709e-05, 'epoch': 1.94}
{'loss': 0.6283, 'grad_norm': 18.308879852294922, 'learning_rate': 1.2396219692719364e-05, 'epoch': 1.97}
{'loss': 0.6276, 'grad_norm': 193.13906860351562, 'learning_rate': 1.1996135313350636e-05, 'epoch': 1.99}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.2015122175216675, 'eval_runtime': 6.3277, 'eval_samples_per_second': 133.382, 'eval_steps_per_second': 16.752, 'epoch': 2.0}
{'loss': 0.1884, 'grad_norm': 50.39581298828125, 'learning_rate': 1.1592693779646405e-05, 'epoch': 2.01}
{'loss': 0.4636, 'grad_norm': 5.622215270996094, 'learning_rate': 1.1186573610485099e-05, 'epoch': 2.04}
{'loss': 0.3982, 'grad_norm': 44.9615478515625, 'learning_rate': 1.0778457829746668e-05, 'epoch': 2.06}
{'loss': 0.584, 'grad_norm': 140.10926818847656, 'learning_rate': 1.036903281758456e-05, 'epoch': 2.09}
{'loss': 0.3144, 'grad_norm': 3.3102869987487793, 'learning_rate': 9.958987156053046e-06, 'epoch': 2.11}
{'loss': 0.4342, 'grad_norm': 15.877002716064453, 'learning_rate': 9.549010471031256e-06, 'epoch': 2.13}
{'loss': 0.3473, 'grad_norm': 60.529483795166016, 'learning_rate': 9.139792272391791e-06, 'epoch': 2.16}
{'loss': 0.387, 'grad_norm': 65.7422866821289, 'learning_rate': 8.732020794364327e-06, 'epoch': 2.18}
{'loss': 0.2493, 'grad_norm': 1.5782440900802612, 'learning_rate': 8.326381838044713e-06, 'epoch': 2.2}
{'loss': 0.4524, 'grad_norm': 56.4810791015625, 'learning_rate': 7.923557617996132e-06, 'epoch': 2.23}
{'loss': 0.6315, 'grad_norm': 32.02418518066406, 'learning_rate': 7.524225614882216e-06, 'epoch': 2.25}
{'loss': 0.283, 'grad_norm': 7.4859619140625, 'learning_rate': 7.12905743606174e-06, 'epoch': 2.27}
{'loss': 0.2603, 'grad_norm': 1.6971173286437988, 'learning_rate': 6.738717686061207e-06, 'epoch': 2.3}
{'loss': 0.4113, 'grad_norm': 79.24764251708984, 'learning_rate': 6.353862848825011e-06, 'epoch': 2.32}
{'loss': 0.2971, 'grad_norm': 2.6368913650512695, 'learning_rate': 5.975140183622958e-06, 'epoch': 2.35}
{'loss': 0.2819, 'grad_norm': 24.301279067993164, 'learning_rate': 5.603186636472156e-06, 'epoch': 2.37}
{'loss': 0.3805, 'grad_norm': 5.371093273162842, 'learning_rate': 5.238627768903957e-06, 'epoch': 2.39}
{'loss': 0.315, 'grad_norm': 69.18685913085938, 'learning_rate': 4.8820767058776895e-06, 'epoch': 2.42}
{'loss': 0.1846, 'grad_norm': 22.528545379638672, 'learning_rate': 4.534133104610507e-06, 'epoch': 2.44}
{'loss': 0.348, 'grad_norm': 86.47562408447266, 'learning_rate': 4.195382146057672e-06, 'epoch': 2.46}
{'loss': 0.5632, 'grad_norm': 0.5207564830780029, 'learning_rate': 3.866393550739415e-06, 'epoch': 2.49}
{'loss': 0.4078, 'grad_norm': 88.20188903808594, 'learning_rate': 3.5477206205695392e-06, 'epoch': 2.51}
{'loss': 0.2083, 'grad_norm': 23.917680740356445, 'learning_rate': 3.2398993082973294e-06, 'epoch': 2.54}
{'loss': 0.2689, 'grad_norm': 37.78529357910156, 'learning_rate': 2.943447316127712e-06, 'epoch': 2.56}
{'loss': 0.2727, 'grad_norm': 69.88945007324219, 'learning_rate': 2.658863225035695e-06, 'epoch': 2.58}
{'loss': 0.1267, 'grad_norm': 0.12254125624895096, 'learning_rate': 2.3866256562394084e-06, 'epoch': 2.61}
{'loss': 0.1849, 'grad_norm': 2.854689836502075, 'learning_rate': 2.127192466241994e-06, 'epoch': 2.63}
{'loss': 0.6309, 'grad_norm': 25.303436279296875, 'learning_rate': 1.880999976796164e-06, 'epoch': 2.65}
{'loss': 0.2823, 'grad_norm': 1.579946517944336, 'learning_rate': 1.6484622410864837e-06, 'epoch': 2.68}
{'loss': 0.2225, 'grad_norm': 0.4664882719516754, 'learning_rate': 1.4299703473635217e-06, 'epoch': 2.7}
{'loss': 0.3839, 'grad_norm': 0.370206743478775, 'learning_rate': 1.22589176120107e-06, 'epoch': 2.73}
{'loss': 0.2105, 'grad_norm': 38.23435592651367, 'learning_rate': 1.036569707482602e-06, 'epoch': 2.75}
{'loss': 0.2553, 'grad_norm': 0.26416444778442383, 'learning_rate': 8.623225931563806e-07, 'epoch': 2.77}
{'loss': 0.3681, 'grad_norm': 13.447306632995605, 'learning_rate': 7.034434717300509e-07, 'epoch': 2.8}
{'loss': 0.1163, 'grad_norm': 0.0851253792643547, 'learning_rate': 5.601995504053193e-07, 'epoch': 2.82}
{'loss': 0.1726, 'grad_norm': 73.10383605957031, 'learning_rate': 4.328317406816751e-07, 'epoch': 2.84}
{'loss': 0.1511, 'grad_norm': 4.455410957336426, 'learning_rate': 3.2155425318489584e-07, 'epoch': 2.87}
{'loss': 0.1431, 'grad_norm': 1.2968225479125977, 'learning_rate': 2.2655423740183925e-07, 'epoch': 2.89}
{'loss': 0.5066, 'grad_norm': 0.11152029037475586, 'learning_rate': 1.4799146692737742e-07, 'epoch': 2.91}
{'loss': 0.3753, 'grad_norm': 154.6046600341797, 'learning_rate': 8.599807075283406e-08, 'epoch': 2.94}
{'loss': 0.2476, 'grad_norm': 24.12568473815918, 'learning_rate': 4.067831104789033e-08, 'epoch': 2.96}
{'loss': 0.4018, 'grad_norm': 21.899866104125977, 'learning_rate': 1.2108407809635624e-08, 'epoch': 2.99}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.366496205329895, 'eval_runtime': 6.2215, 'eval_samples_per_second': 135.659, 'eval_steps_per_second': 17.038, 'epoch': 3.0}
{'train_runtime': 435.5094, 'train_samples_per_second': 23.242, 'train_steps_per_second': 2.907, 'train_loss': 0.398842003202363, 'epoch': 3.0}

  0%|          | 0/106 [00:00<?, ?it/s]

Balanced Accuracy: 0.39718867195669283

In [73]:
# Define training arguments with cosine scheduler
training_args = TrainingArguments(
    output_dir="./linear",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=1,
    load_best_model_at_end=True,
    learning_rate=2e-5,
    per_device_train_batch_size=8,  # Use a smaller batch size
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    lr_scheduler_type="linear",  # Use cosine scheduler
    warmup_steps=500,
    logging_dir='./logs',
    logging_steps=10,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)

/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [74]:
# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

  0%|          | 0/1266 [00:00<?, ?it/s]

{'loss': 0.597, 'grad_norm': 19.70569610595703, 'learning_rate': 3.2e-07, 'epoch': 0.02}
{'loss': 0.592, 'grad_norm': 37.580482482910156, 'learning_rate': 7.2e-07, 'epoch': 0.05}
{'loss': 0.3416, 'grad_norm': 19.73887825012207, 'learning_rate': 1.12e-06, 'epoch': 0.07}
{'loss': 0.3186, 'grad_norm': 49.040733337402344, 'learning_rate': 1.52e-06, 'epoch': 0.09}
{'loss': 0.6037, 'grad_norm': 30.002079010009766, 'learning_rate': 1.9200000000000003e-06, 'epoch': 0.12}
{'loss': 0.4517, 'grad_norm': 0.6154088377952576, 'learning_rate': 2.3200000000000002e-06, 'epoch': 0.14}
{'loss': 0.415, 'grad_norm': 42.46630096435547, 'learning_rate': 2.7200000000000002e-06, 'epoch': 0.17}
{'loss': 0.3691, 'grad_norm': 5.367023468017578, 'learning_rate': 3.12e-06, 'epoch': 0.19}
{'loss': 0.268, 'grad_norm': 25.90089225769043, 'learning_rate': 3.52e-06, 'epoch': 0.21}
{'loss': 0.2645, 'grad_norm': 0.4082046449184418, 'learning_rate': 3.920000000000001e-06, 'epoch': 0.24}
{'loss': 0.2467, 'grad_norm': 9.408897399902344, 'learning_rate': 4.2800000000000005e-06, 'epoch': 0.26}
{'loss': 0.5589, 'grad_norm': 24.0662784576416, 'learning_rate': 4.680000000000001e-06, 'epoch': 0.28}
{'loss': 0.3013, 'grad_norm': 28.902023315429688, 'learning_rate': 5.0800000000000005e-06, 'epoch': 0.31}
{'loss': 0.5254, 'grad_norm': 17.369028091430664, 'learning_rate': 5.480000000000001e-06, 'epoch': 0.33}
{'loss': 0.273, 'grad_norm': 1.254219889640808, 'learning_rate': 5.8800000000000005e-06, 'epoch': 0.36}
{'loss': 0.245, 'grad_norm': 0.46951058506965637, 'learning_rate': 6.280000000000001e-06, 'epoch': 0.38}
{'loss': 0.2288, 'grad_norm': 2.1271345615386963, 'learning_rate': 6.680000000000001e-06, 'epoch': 0.4}
{'loss': 0.3874, 'grad_norm': 29.25868034362793, 'learning_rate': 7.08e-06, 'epoch': 0.43}
{'loss': 0.1849, 'grad_norm': 35.56846237182617, 'learning_rate': 7.48e-06, 'epoch': 0.45}
{'loss': 0.1804, 'grad_norm': 4.281733512878418, 'learning_rate': 7.88e-06, 'epoch': 0.47}
{'loss': 0.1379, 'grad_norm': 12.987378120422363, 'learning_rate': 8.28e-06, 'epoch': 0.5}
{'loss': 0.31, 'grad_norm': 0.14813342690467834, 'learning_rate': 8.68e-06, 'epoch': 0.52}
{'loss': 0.0812, 'grad_norm': 43.179786682128906, 'learning_rate': 9.080000000000001e-06, 'epoch': 0.55}
{'loss': 0.1979, 'grad_norm': 0.10147299617528915, 'learning_rate': 9.48e-06, 'epoch': 0.57}
{'loss': 0.1896, 'grad_norm': 0.06041260436177254, 'learning_rate': 9.88e-06, 'epoch': 0.59}
{'loss': 0.1762, 'grad_norm': 0.16545523703098297, 'learning_rate': 1.0280000000000002e-05, 'epoch': 0.62}
{'loss': 0.4284, 'grad_norm': 0.035171136260032654, 'learning_rate': 1.0680000000000001e-05, 'epoch': 0.64}
{'loss': 0.2528, 'grad_norm': 4.725983619689941, 'learning_rate': 1.1080000000000002e-05, 'epoch': 0.66}
{'loss': 0.0936, 'grad_norm': 0.30943137407302856, 'learning_rate': 1.148e-05, 'epoch': 0.69}
{'loss': 0.0739, 'grad_norm': 0.23418360948562622, 'learning_rate': 1.188e-05, 'epoch': 0.71}
{'loss': 0.1909, 'grad_norm': 20.587038040161133, 'learning_rate': 1.2280000000000001e-05, 'epoch': 0.73}
{'loss': 0.1975, 'grad_norm': 16.75295066833496, 'learning_rate': 1.268e-05, 'epoch': 0.76}
{'loss': 0.3755, 'grad_norm': 6.72258186340332, 'learning_rate': 1.3080000000000002e-05, 'epoch': 0.78}
{'loss': 0.2983, 'grad_norm': 0.06048094853758812, 'learning_rate': 1.3480000000000001e-05, 'epoch': 0.81}
{'loss': 0.1263, 'grad_norm': 66.94432830810547, 'learning_rate': 1.3880000000000001e-05, 'epoch': 0.83}
{'loss': 0.184, 'grad_norm': 0.11981905996799469, 'learning_rate': 1.428e-05, 'epoch': 0.85}
{'loss': 0.0876, 'grad_norm': 39.568328857421875, 'learning_rate': 1.4680000000000002e-05, 'epoch': 0.88}
{'loss': 0.1106, 'grad_norm': 0.2368306666612625, 'learning_rate': 1.5080000000000001e-05, 'epoch': 0.9}
{'loss': 0.2156, 'grad_norm': 9.109861373901367, 'learning_rate': 1.544e-05, 'epoch': 0.92}
{'loss': 0.1732, 'grad_norm': 50.01869201660156, 'learning_rate': 1.584e-05, 'epoch': 0.95}
{'loss': 0.3077, 'grad_norm': 7.306163787841797, 'learning_rate': 1.6240000000000004e-05, 'epoch': 0.97}
{'loss': 0.224, 'grad_norm': 3.295644521713257, 'learning_rate': 1.664e-05, 'epoch': 1.0}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.431194543838501, 'eval_runtime': 6.3379, 'eval_samples_per_second': 133.167, 'eval_steps_per_second': 16.725, 'epoch': 1.0}
{'loss': 0.3233, 'grad_norm': 66.324462890625, 'learning_rate': 1.704e-05, 'epoch': 1.02}
{'loss': 0.2667, 'grad_norm': 104.98839569091797, 'learning_rate': 1.7440000000000002e-05, 'epoch': 1.04}
{'loss': 0.6225, 'grad_norm': 84.27437591552734, 'learning_rate': 1.7840000000000002e-05, 'epoch': 1.07}
{'loss': 0.2582, 'grad_norm': 28.592395782470703, 'learning_rate': 1.824e-05, 'epoch': 1.09}
{'loss': 0.3869, 'grad_norm': 115.58715057373047, 'learning_rate': 1.864e-05, 'epoch': 1.11}
{'loss': 0.4067, 'grad_norm': 100.38384246826172, 'learning_rate': 1.904e-05, 'epoch': 1.14}
{'loss': 0.2948, 'grad_norm': 74.11288452148438, 'learning_rate': 1.944e-05, 'epoch': 1.16}
{'loss': 0.2696, 'grad_norm': 87.64501190185547, 'learning_rate': 1.9840000000000003e-05, 'epoch': 1.18}
{'loss': 0.8311, 'grad_norm': 111.31649017333984, 'learning_rate': 1.9843342036553526e-05, 'epoch': 1.21}
{'loss': 0.4613, 'grad_norm': 19.60608673095703, 'learning_rate': 1.95822454308094e-05, 'epoch': 1.23}
{'loss': 0.4394, 'grad_norm': 17.56150245666504, 'learning_rate': 1.9321148825065278e-05, 'epoch': 1.26}
{'loss': 0.5436, 'grad_norm': 43.4123420715332, 'learning_rate': 1.906005221932115e-05, 'epoch': 1.28}
{'loss': 0.6869, 'grad_norm': 34.51637649536133, 'learning_rate': 1.8798955613577027e-05, 'epoch': 1.3}
{'loss': 0.3614, 'grad_norm': 0.1361865997314453, 'learning_rate': 1.85378590078329e-05, 'epoch': 1.33}
{'loss': 0.3501, 'grad_norm': 18.29876136779785, 'learning_rate': 1.8276762402088773e-05, 'epoch': 1.35}
{'loss': 0.6254, 'grad_norm': 67.54075622558594, 'learning_rate': 1.8015665796344648e-05, 'epoch': 1.37}
{'loss': 0.4799, 'grad_norm': 17.78715705871582, 'learning_rate': 1.7754569190600522e-05, 'epoch': 1.4}
{'loss': 0.418, 'grad_norm': 57.10627365112305, 'learning_rate': 1.74934725848564e-05, 'epoch': 1.42}
{'loss': 0.3138, 'grad_norm': 119.82646179199219, 'learning_rate': 1.723237597911227e-05, 'epoch': 1.45}
{'loss': 0.3572, 'grad_norm': 31.287424087524414, 'learning_rate': 1.697127937336815e-05, 'epoch': 1.47}
{'loss': 0.6549, 'grad_norm': 95.16863250732422, 'learning_rate': 1.671018276762402e-05, 'epoch': 1.49}
{'loss': 0.3417, 'grad_norm': 8.28176212310791, 'learning_rate': 1.64490861618799e-05, 'epoch': 1.52}
{'loss': 0.2315, 'grad_norm': 27.185932159423828, 'learning_rate': 1.6187989556135773e-05, 'epoch': 1.54}
{'loss': 0.1664, 'grad_norm': 0.5416810512542725, 'learning_rate': 1.5926892950391644e-05, 'epoch': 1.56}
{'loss': 0.4441, 'grad_norm': 0.48205143213272095, 'learning_rate': 1.5665796344647522e-05, 'epoch': 1.59}
{'loss': 0.2626, 'grad_norm': 37.66995620727539, 'learning_rate': 1.5404699738903393e-05, 'epoch': 1.61}
{'loss': 0.3637, 'grad_norm': 24.151891708374023, 'learning_rate': 1.514360313315927e-05, 'epoch': 1.64}
{'loss': 0.261, 'grad_norm': 1.5689202547073364, 'learning_rate': 1.4882506527415146e-05, 'epoch': 1.66}
{'loss': 0.9319, 'grad_norm': 98.58562469482422, 'learning_rate': 1.4621409921671019e-05, 'epoch': 1.68}
{'loss': 0.2343, 'grad_norm': 1.5550892353057861, 'learning_rate': 1.4360313315926895e-05, 'epoch': 1.71}
{'loss': 0.3354, 'grad_norm': 107.38740539550781, 'learning_rate': 1.4099216710182768e-05, 'epoch': 1.73}
{'loss': 0.0693, 'grad_norm': 128.7261199951172, 'learning_rate': 1.3838120104438644e-05, 'epoch': 1.75}
{'loss': 0.5916, 'grad_norm': 0.669508159160614, 'learning_rate': 1.3577023498694517e-05, 'epoch': 1.78}
{'loss': 0.351, 'grad_norm': 117.32817077636719, 'learning_rate': 1.3315926892950393e-05, 'epoch': 1.8}
{'loss': 0.3607, 'grad_norm': 0.8661297559738159, 'learning_rate': 1.3054830287206268e-05, 'epoch': 1.82}
{'loss': 0.4968, 'grad_norm': 110.37283325195312, 'learning_rate': 1.2793733681462141e-05, 'epoch': 1.85}
{'loss': 0.3449, 'grad_norm': 49.81535339355469, 'learning_rate': 1.2532637075718017e-05, 'epoch': 1.87}
{'loss': 0.6092, 'grad_norm': 42.532684326171875, 'learning_rate': 1.227154046997389e-05, 'epoch': 1.9}
{'loss': 0.1262, 'grad_norm': 0.18114158511161804, 'learning_rate': 1.2010443864229766e-05, 'epoch': 1.92}
{'loss': 0.2762, 'grad_norm': 72.3251724243164, 'learning_rate': 1.174934725848564e-05, 'epoch': 1.94}
{'loss': 0.5966, 'grad_norm': 51.37623977661133, 'learning_rate': 1.1488250652741515e-05, 'epoch': 1.97}
{'loss': 0.6453, 'grad_norm': 66.6299819946289, 'learning_rate': 1.122715404699739e-05, 'epoch': 1.99}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.3310879468917847, 'eval_runtime': 6.3371, 'eval_samples_per_second': 133.184, 'eval_steps_per_second': 16.727, 'epoch': 2.0}
{'loss': 0.2175, 'grad_norm': 3.333611011505127, 'learning_rate': 1.0966057441253265e-05, 'epoch': 2.01}
{'loss': 0.3224, 'grad_norm': 0.24859365820884705, 'learning_rate': 1.0704960835509139e-05, 'epoch': 2.04}
{'loss': 0.2518, 'grad_norm': 99.69461822509766, 'learning_rate': 1.0443864229765015e-05, 'epoch': 2.06}
{'loss': 0.6263, 'grad_norm': 155.5381317138672, 'learning_rate': 1.0182767624020888e-05, 'epoch': 2.09}
{'loss': 0.2839, 'grad_norm': 1.1282457113265991, 'learning_rate': 9.921671018276763e-06, 'epoch': 2.11}
{'loss': 0.2168, 'grad_norm': 3.824004888534546, 'learning_rate': 9.660574412532639e-06, 'epoch': 2.13}
{'loss': 0.2782, 'grad_norm': 0.8301821947097778, 'learning_rate': 9.399477806788514e-06, 'epoch': 2.16}
{'loss': 0.4057, 'grad_norm': 46.02900695800781, 'learning_rate': 9.138381201044387e-06, 'epoch': 2.18}
{'loss': 0.1885, 'grad_norm': 61.34645462036133, 'learning_rate': 8.877284595300261e-06, 'epoch': 2.2}
{'loss': 0.4433, 'grad_norm': 102.52181243896484, 'learning_rate': 8.616187989556136e-06, 'epoch': 2.23}
{'loss': 0.5418, 'grad_norm': 64.58696746826172, 'learning_rate': 8.35509138381201e-06, 'epoch': 2.25}
{'loss': 0.3268, 'grad_norm': 109.06673431396484, 'learning_rate': 8.093994778067887e-06, 'epoch': 2.27}
{'loss': 0.2094, 'grad_norm': 6.408008098602295, 'learning_rate': 7.832898172323761e-06, 'epoch': 2.3}
{'loss': 0.3105, 'grad_norm': 105.37552642822266, 'learning_rate': 7.571801566579635e-06, 'epoch': 2.32}
{'loss': 0.1733, 'grad_norm': 0.5743674039840698, 'learning_rate': 7.336814621409923e-06, 'epoch': 2.35}
{'loss': 0.2133, 'grad_norm': 13.129349708557129, 'learning_rate': 7.075718015665796e-06, 'epoch': 2.37}
{'loss': 0.3414, 'grad_norm': 8.721809387207031, 'learning_rate': 6.814621409921671e-06, 'epoch': 2.39}
{'loss': 0.4916, 'grad_norm': 42.53134536743164, 'learning_rate': 6.553524804177546e-06, 'epoch': 2.42}
{'loss': 0.2313, 'grad_norm': 80.1993408203125, 'learning_rate': 6.292428198433421e-06, 'epoch': 2.44}
{'loss': 0.3586, 'grad_norm': 86.02961730957031, 'learning_rate': 6.0313315926892955e-06, 'epoch': 2.46}
{'loss': 0.3294, 'grad_norm': 34.55940246582031, 'learning_rate': 5.77023498694517e-06, 'epoch': 2.49}
{'loss': 0.2735, 'grad_norm': 68.71211242675781, 'learning_rate': 5.509138381201045e-06, 'epoch': 2.51}
{'loss': 0.1602, 'grad_norm': 35.691123962402344, 'learning_rate': 5.248041775456919e-06, 'epoch': 2.54}
{'loss': 0.2537, 'grad_norm': 78.31477355957031, 'learning_rate': 4.986945169712794e-06, 'epoch': 2.56}
{'loss': 0.1514, 'grad_norm': 116.9940185546875, 'learning_rate': 4.725848563968668e-06, 'epoch': 2.58}
{'loss': 0.184, 'grad_norm': 48.44630813598633, 'learning_rate': 4.464751958224544e-06, 'epoch': 2.61}
{'loss': 0.2798, 'grad_norm': 98.25816345214844, 'learning_rate': 4.229765013054831e-06, 'epoch': 2.63}
{'loss': 0.578, 'grad_norm': 18.265548706054688, 'learning_rate': 3.968668407310705e-06, 'epoch': 2.65}
{'loss': 0.2205, 'grad_norm': 5.630443572998047, 'learning_rate': 3.7075718015665803e-06, 'epoch': 2.68}
{'loss': 0.2798, 'grad_norm': 0.3174472749233246, 'learning_rate': 3.4464751958224545e-06, 'epoch': 2.7}
{'loss': 0.2264, 'grad_norm': 0.2204279750585556, 'learning_rate': 3.185378590078329e-06, 'epoch': 2.73}
{'loss': 0.1855, 'grad_norm': 53.57929992675781, 'learning_rate': 2.924281984334204e-06, 'epoch': 2.75}
{'loss': 0.3077, 'grad_norm': 0.16019664704799652, 'learning_rate': 2.6631853785900786e-06, 'epoch': 2.77}
{'loss': 0.5478, 'grad_norm': 7.6678876876831055, 'learning_rate': 2.402088772845953e-06, 'epoch': 2.8}
{'loss': 0.1708, 'grad_norm': 0.04614794999361038, 'learning_rate': 2.1409921671018277e-06, 'epoch': 2.82}
{'loss': 0.2054, 'grad_norm': 97.05473327636719, 'learning_rate': 1.8798955613577025e-06, 'epoch': 2.84}
{'loss': 0.2106, 'grad_norm': 0.2770477831363678, 'learning_rate': 1.618798955613577e-06, 'epoch': 2.87}
{'loss': 0.1152, 'grad_norm': 0.2580859363079071, 'learning_rate': 1.3577023498694519e-06, 'epoch': 2.89}
{'loss': 0.2826, 'grad_norm': 0.13524501025676727, 'learning_rate': 1.0966057441253265e-06, 'epoch': 2.91}
{'loss': 0.15, 'grad_norm': 156.37562561035156, 'learning_rate': 8.355091383812011e-07, 'epoch': 2.94}
{'loss': 0.2508, 'grad_norm': 74.41352844238281, 'learning_rate': 5.744125326370758e-07, 'epoch': 2.96}
{'loss': 0.3914, 'grad_norm': 58.10533142089844, 'learning_rate': 3.133159268929504e-07, 'epoch': 2.99}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.5171339511871338, 'eval_runtime': 6.3044, 'eval_samples_per_second': 133.875, 'eval_steps_per_second': 16.814, 'epoch': 3.0}
{'train_runtime': 435.9837, 'train_samples_per_second': 23.216, 'train_steps_per_second': 2.904, 'train_loss': 0.3290456482113632, 'epoch': 3.0}

  0%|          | 0/106 [00:00<?, ?it/s]

Balanced Accuracy: 0.4377805587134403

In [3]:
# Tokenize the dataset
model_name = "FacebookAI/roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Load the model
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)

Map:   0%|          | 0/3374 [00:00<?, ? examples/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [4]:
# Define training arguments with cosine scheduler
training_args = TrainingArguments(
    output_dir="./linearRoberta",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=1,
    load_best_model_at_end=True,
    learning_rate=2e-5,
    per_device_train_batch_size=32,  # Use a smaller batch size
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    lr_scheduler_type="linear",  # Use cosine scheduler
    warmup_steps=500,
    logging_dir='./logs',
    logging_steps=10,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)


# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/318 [00:00<?, ?it/s]

{'loss': 1.9691, 'grad_norm': 6.582851409912109, 'learning_rate': 4.0000000000000003e-07, 'epoch': 0.09}
{'loss': 1.952, 'grad_norm': 5.6855082511901855, 'learning_rate': 8.000000000000001e-07, 'epoch': 0.19}
{'loss': 1.9579, 'grad_norm': 5.854674816131592, 'learning_rate': 1.2000000000000002e-06, 'epoch': 0.28}
{'loss': 1.8995, 'grad_norm': 6.502702236175537, 'learning_rate': 1.6000000000000001e-06, 'epoch': 0.38}
{'loss': 1.8717, 'grad_norm': 5.269619941711426, 'learning_rate': 2.0000000000000003e-06, 'epoch': 0.47}
{'loss': 1.8073, 'grad_norm': 4.189080238342285, 'learning_rate': 2.4000000000000003e-06, 'epoch': 0.57}
{'loss': 1.7072, 'grad_norm': 6.925071716308594, 'learning_rate': 2.8000000000000003e-06, 'epoch': 0.66}
{'loss': 1.5445, 'grad_norm': 7.932063102722168, 'learning_rate': 3.2000000000000003e-06, 'epoch': 0.75}
{'loss': 1.3102, 'grad_norm': 7.009544372558594, 'learning_rate': 3.6000000000000003e-06, 'epoch': 0.85}
{'loss': 1.1538, 'grad_norm': 3.4813458919525146, 'learning_rate': 4.000000000000001e-06, 'epoch': 0.94}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 1.1820622682571411, 'eval_runtime': 4.7402, 'eval_samples_per_second': 178.052, 'eval_steps_per_second': 5.696, 'epoch': 1.0}
{'loss': 1.2259, 'grad_norm': 3.4648213386535645, 'learning_rate': 4.4e-06, 'epoch': 1.04}
{'loss': 1.2036, 'grad_norm': 4.418182849884033, 'learning_rate': 4.800000000000001e-06, 'epoch': 1.13}
{'loss': 1.2106, 'grad_norm': 4.172192573547363, 'learning_rate': 5.2e-06, 'epoch': 1.23}
{'loss': 1.1154, 'grad_norm': 4.2575154304504395, 'learning_rate': 5.600000000000001e-06, 'epoch': 1.32}
{'loss': 1.1125, 'grad_norm': 4.374039649963379, 'learning_rate': 6e-06, 'epoch': 1.42}
{'loss': 1.0806, 'grad_norm': 4.394668102264404, 'learning_rate': 6.4000000000000006e-06, 'epoch': 1.51}
{'loss': 1.1727, 'grad_norm': 6.111232280731201, 'learning_rate': 6.800000000000001e-06, 'epoch': 1.6}
{'loss': 0.9637, 'grad_norm': 5.012210369110107, 'learning_rate': 7.2000000000000005e-06, 'epoch': 1.7}
{'loss': 1.0041, 'grad_norm': 6.990807056427002, 'learning_rate': 7.600000000000001e-06, 'epoch': 1.79}
{'loss': 1.005, 'grad_norm': 6.728612422943115, 'learning_rate': 8.000000000000001e-06, 'epoch': 1.89}
{'loss': 1.0101, 'grad_norm': 5.67996883392334, 'learning_rate': 8.400000000000001e-06, 'epoch': 1.98}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.9748303294181824, 'eval_runtime': 4.7704, 'eval_samples_per_second': 176.925, 'eval_steps_per_second': 5.66, 'epoch': 2.0}
{'loss': 0.9359, 'grad_norm': 4.680797100067139, 'learning_rate': 8.8e-06, 'epoch': 2.08}
{'loss': 0.9008, 'grad_norm': 6.928817272186279, 'learning_rate': 9.200000000000002e-06, 'epoch': 2.17}
{'loss': 0.9228, 'grad_norm': 13.425155639648438, 'learning_rate': 9.600000000000001e-06, 'epoch': 2.26}
{'loss': 0.8582, 'grad_norm': 8.33742904663086, 'learning_rate': 1e-05, 'epoch': 2.36}
{'loss': 0.9631, 'grad_norm': 13.774367332458496, 'learning_rate': 1.04e-05, 'epoch': 2.45}
{'loss': 0.9402, 'grad_norm': 11.575005531311035, 'learning_rate': 1.0800000000000002e-05, 'epoch': 2.55}
{'loss': 0.8572, 'grad_norm': 19.969196319580078, 'learning_rate': 1.1200000000000001e-05, 'epoch': 2.64}
{'loss': 0.8795, 'grad_norm': 8.901304244995117, 'learning_rate': 1.16e-05, 'epoch': 2.74}
{'loss': 0.7947, 'grad_norm': 10.369805335998535, 'learning_rate': 1.2e-05, 'epoch': 2.83}
{'loss': 0.8928, 'grad_norm': 17.226829528808594, 'learning_rate': 1.2400000000000002e-05, 'epoch': 2.92}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8384498357772827, 'eval_runtime': 4.7694, 'eval_samples_per_second': 176.962, 'eval_steps_per_second': 5.661, 'epoch': 3.0}
{'train_runtime': 207.4917, 'train_samples_per_second': 48.783, 'train_steps_per_second': 1.533, 'train_loss': 1.2221669850859251, 'epoch': 3.0}

  0%|          | 0/27 [00:00<?, ?it/s]

Balanced Accuracy: 0.32985425223384507

In [76]:
training_args = TrainingArguments(
    output_dir="./roberta",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=7,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)


# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/742 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.9491597414016724, 'eval_runtime': 2.453, 'eval_samples_per_second': 344.069, 'eval_steps_per_second': 11.007, 'epoch': 1.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8134118914604187, 'eval_runtime': 2.462, 'eval_samples_per_second': 342.808, 'eval_steps_per_second': 10.967, 'epoch': 2.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.7614051699638367, 'eval_runtime': 2.4542, 'eval_samples_per_second': 343.896, 'eval_steps_per_second': 11.001, 'epoch': 3.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8026868104934692, 'eval_runtime': 2.4001, 'eval_samples_per_second': 351.651, 'eval_steps_per_second': 11.25, 'epoch': 4.0}
{'loss': 0.755, 'grad_norm': 5.745728492736816, 'learning_rate': 6.576819407008087e-06, 'epoch': 4.72}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.820533812046051, 'eval_runtime': 2.4752, 'eval_samples_per_second': 340.987, 'eval_steps_per_second': 10.908, 'epoch': 5.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8475618958473206, 'eval_runtime': 2.4463, 'eval_samples_per_second': 345.01, 'eval_steps_per_second': 11.037, 'epoch': 6.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8558804988861084, 'eval_runtime': 2.3892, 'eval_samples_per_second': 353.252, 'eval_steps_per_second': 11.301, 'epoch': 7.0}
{'train_runtime': 334.1379, 'train_samples_per_second': 70.683, 'train_steps_per_second': 2.221, 'train_loss': 0.6260320658311047, 'epoch': 7.0}

  0%|          | 0/27 [00:00<?, ?it/s]

Balanced Accuracy: 0.39755114307636363

In [77]:
training_args = TrainingArguments(
    output_dir="./roberta3",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)


# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/318 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8476194143295288, 'eval_runtime': 2.3843, 'eval_samples_per_second': 353.987, 'eval_steps_per_second': 11.324, 'epoch': 1.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8968831300735474, 'eval_runtime': 2.3067, 'eval_samples_per_second': 365.89, 'eval_steps_per_second': 11.705, 'epoch': 2.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.9237827062606812, 'eval_runtime': 2.4462, 'eval_samples_per_second': 345.029, 'eval_steps_per_second': 11.038, 'epoch': 3.0}
{'train_runtime': 140.698, 'train_samples_per_second': 71.941, 'train_steps_per_second': 2.26, 'train_loss': 0.39516446575428704, 'epoch': 3.0}

  0%|          | 0/27 [00:00<?, ?it/s]

Balanced Accuracy: 0.4501072646720757

In [5]:
# Tokenize the dataset
model_name = "google-bert/bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Load the model
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)

Map:   0%|          | 0/3374 [00:00<?, ? examples/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
training_args = TrainingArguments(
    output_dir="./bert3",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)


# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

In [6]:
training_args = TrainingArguments(
    output_dir="./bert",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    num_train_epochs=7,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)


# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/371 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

{'eval_loss': 1.0882431268692017, 'eval_runtime': 3.1895, 'eval_samples_per_second': 264.618, 'eval_steps_per_second': 4.389, 'epoch': 1.0}

  0%|          | 0/14 [00:00<?, ?it/s]

{'eval_loss': 0.9861422777175903, 'eval_runtime': 3.1307, 'eval_samples_per_second': 269.591, 'eval_steps_per_second': 4.472, 'epoch': 2.0}

  0%|          | 0/14 [00:00<?, ?it/s]

{'eval_loss': 0.9292097687721252, 'eval_runtime': 3.1271, 'eval_samples_per_second': 269.901, 'eval_steps_per_second': 4.477, 'epoch': 3.0}

  0%|          | 0/14 [00:00<?, ?it/s]

{'eval_loss': 0.926419198513031, 'eval_runtime': 3.1452, 'eval_samples_per_second': 268.346, 'eval_steps_per_second': 4.451, 'epoch': 4.0}

  0%|          | 0/14 [00:00<?, ?it/s]

{'eval_loss': 0.91395103931427, 'eval_runtime': 3.103, 'eval_samples_per_second': 271.998, 'eval_steps_per_second': 4.512, 'epoch': 5.0}

  0%|          | 0/14 [00:00<?, ?it/s]

{'eval_loss': 0.9282215237617493, 'eval_runtime': 3.1387, 'eval_samples_per_second': 268.898, 'eval_steps_per_second': 4.46, 'epoch': 6.0}

  0%|          | 0/14 [00:00<?, ?it/s]

{'eval_loss': 0.9276850819587708, 'eval_runtime': 3.1785, 'eval_samples_per_second': 265.536, 'eval_steps_per_second': 4.405, 'epoch': 7.0}
{'train_runtime': 357.3766, 'train_samples_per_second': 66.087, 'train_steps_per_second': 1.038, 'train_loss': 0.7913979584316038, 'epoch': 7.0}

  0%|          | 0/14 [00:00<?, ?it/s]

Balanced Accuracy: 0.34046317452875957

In [7]:
training_args = TrainingArguments(
    output_dir="./bert3",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)


# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/159 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

{'eval_loss': 0.9466595649719238, 'eval_runtime': 3.129, 'eval_samples_per_second': 269.734, 'eval_steps_per_second': 4.474, 'epoch': 1.0}

  0%|          | 0/14 [00:00<?, ?it/s]

{'eval_loss': 0.9691168069839478, 'eval_runtime': 3.2148, 'eval_samples_per_second': 262.537, 'eval_steps_per_second': 4.355, 'epoch': 2.0}

  0%|          | 0/14 [00:00<?, ?it/s]

{'eval_loss': 0.9971573948860168, 'eval_runtime': 3.1651, 'eval_samples_per_second': 266.661, 'eval_steps_per_second': 4.423, 'epoch': 3.0}
{'train_runtime': 153.9716, 'train_samples_per_second': 65.739, 'train_steps_per_second': 1.033, 'train_loss': 0.44172625271779187, 'epoch': 3.0}

  0%|          | 0/14 [00:00<?, ?it/s]

Balanced Accuracy: 0.33307720221441817

In [1]:
import pandas as pd
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import balanced_accuracy_score
import optuna
import torch
import gc

# Load the CSV file
file_path = f'{DATA_DIR}/train_eng_v2.csv'
df = pd.read_csv(file_path)

# Create a label mapping
label_mapping = {
    'Politik': 0,
    'Sosial Budaya': 1,
    'Ekonomi': 2,
    'Pertahanan dan Keamanan': 3,
    'Ideologi': 4,
    'Sumber Daya Alam': 5,
    'Demografi': 6,
    'Geografi': 7
}

# Apply the label mapping
df['label'] = df['label'].map(label_mapping)

# Split the DataFrame into training and validation sets
train_df, val_df = train_test_split(df, test_size=0.2, stratify=df['label'], random_state=42)

# Convert DataFrames to Datasets
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

# Combine into a DatasetDict
dataset = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset
})

# Tokenize the dataset
model_name = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Define the objective function for Optuna
def objective(trial):
    # Hyperparameters to tune
    learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
    batch_size = trial.suggest_categorical('batch_size', [8, 16, 32])
    num_train_epochs = trial.suggest_int('num_train_epochs', 2, 10)

    # Clear GPU memory
    torch.cuda.empty_cache()
    gc.collect()

    # Define the model
    model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)

    # Define training arguments
    training_args = TrainingArguments(
        output_dir="./results",
        evaluation_strategy="epoch",
        save_strategy="epoch",
        learning_rate=learning_rate,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        num_train_epochs=num_train_epochs,
        weight_decay=0.01,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
    )

    # Define Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_datasets['train'],
        eval_dataset=tokenized_datasets['validation'],
    )

    # Train the model
    trainer.train()

    # Evaluate the model
    eval_result = trainer.evaluate()
    
    # Return the evaluation metric to be optimized
    return eval_result['eval_loss']

# Callback to save the best trial
def save_best_trial(study, trial):
    if study.best_trial == trial:
        with open("best_hyperparameters.txt", "w") as f:
            f.write(str(study.best_params))

# Create a study and optimize the objective function
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=20, callbacks=[save_best_trial])

# Get the best hyperparameters
best_hyperparameters = study.best_params
print(best_hyperparameters)

# Save the best hyperparameters to a file
with open("best_hyperparameters.txt", "w") as f:
    f.write(str(best_hyperparameters))

# Clear GPU memory before final training
torch.cuda.empty_cache()
gc.collect()

# Train and evaluate the model with the best hyperparameters
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)

# Define training arguments with the best hyperparameters
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=best_hyperparameters['learning_rate'],
    per_device_train_batch_size=best_hyperparameters['batch_size'],
    per_device_eval_batch_size=best_hyperparameters['batch_size'],
    num_train_epochs=best_hyperparameters['num_train_epochs'],
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer with the best hyperparameters
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)

# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

Map:   0%|          | 0/3374 [00:00<?, ? examples/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

[I 2024-06-02 15:03:30,640] A new study created in memory with name: no-name-2614de97-f129-4da5-bee8-14bcecd207be
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/844 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 2.014237403869629, 'eval_runtime': 4.7366, 'eval_samples_per_second': 178.187, 'eval_steps_per_second': 11.189, 'epoch': 1.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 2.011507987976074, 'eval_runtime': 4.655, 'eval_samples_per_second': 181.312, 'eval_steps_per_second': 11.386, 'epoch': 2.0}
{'loss': 2.01, 'grad_norm': 3.8386707305908203, 'learning_rate': 5.11968431911038e-09, 'epoch': 2.37}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 2.00986909866333, 'eval_runtime': 4.6118, 'eval_samples_per_second': 183.008, 'eval_steps_per_second': 11.492, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 2.0094070434570312, 'eval_runtime': 4.7405, 'eval_samples_per_second': 178.04, 'eval_steps_per_second': 11.18, 'epoch': 4.0}
{'train_runtime': 284.5508, 'train_samples_per_second': 47.429, 'train_steps_per_second': 2.966, 'train_loss': 2.008282051267217, 'epoch': 4.0}

  0%|          | 0/53 [00:00<?, ?it/s]

[I 2024-06-02 15:08:53,437] Trial 0 finished with value: 2.0094070434570312 and parameters: {'learning_rate': 1.2561085945724304e-08, 'batch_size': 16, 'num_train_epochs': 4}. Best is trial 0 with value: 2.0094070434570312.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/2532 [00:00<?, ?it/s]

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.2010592222213745, 'eval_runtime': 4.7073, 'eval_samples_per_second': 179.297, 'eval_steps_per_second': 22.518, 'epoch': 1.0}
{'loss': 1.5322, 'grad_norm': 7.796987533569336, 'learning_rate': 5.941449281360922e-07, 'epoch': 1.18}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.147295594215393, 'eval_runtime': 4.6913, 'eval_samples_per_second': 179.907, 'eval_steps_per_second': 22.595, 'epoch': 2.0}
{'loss': 1.1853, 'grad_norm': 8.718728065490723, 'learning_rate': 4.479478493624475e-07, 'epoch': 2.37}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.108818769454956, 'eval_runtime': 4.7558, 'eval_samples_per_second': 177.467, 'eval_steps_per_second': 22.289, 'epoch': 3.0}
{'loss': 1.1086, 'grad_norm': 8.470165252685547, 'learning_rate': 3.017507705888027e-07, 'epoch': 3.55}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.0716921091079712, 'eval_runtime': 4.7171, 'eval_samples_per_second': 178.924, 'eval_steps_per_second': 22.471, 'epoch': 4.0}
{'loss': 1.0899, 'grad_norm': 10.19553279876709, 'learning_rate': 1.5555369181515802e-07, 'epoch': 4.74}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.054720163345337, 'eval_runtime': 3.7957, 'eval_samples_per_second': 222.358, 'eval_steps_per_second': 27.927, 'epoch': 5.0}
{'loss': 1.0637, 'grad_norm': 17.010055541992188, 'learning_rate': 9.356613041513263e-09, 'epoch': 5.92}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.0490789413452148, 'eval_runtime': 3.7803, 'eval_samples_per_second': 223.264, 'eval_steps_per_second': 28.04, 'epoch': 6.0}
{'train_runtime': 443.9859, 'train_samples_per_second': 45.596, 'train_steps_per_second': 5.703, 'train_loss': 1.195037162322757, 'epoch': 6.0}

  0%|          | 0/106 [00:00<?, ?it/s]

[I 2024-06-02 15:16:23,362] Trial 1 finished with value: 1.0490789413452148 and parameters: {'learning_rate': 7.403420069097369e-07, 'batch_size': 8, 'num_train_epochs': 6}. Best is trial 1 with value: 1.0490789413452148.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1055 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.9667824506759644, 'eval_runtime': 3.6892, 'eval_samples_per_second': 228.776, 'eval_steps_per_second': 14.366, 'epoch': 1.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.9638969898223877, 'eval_runtime': 3.6817, 'eval_samples_per_second': 229.242, 'eval_steps_per_second': 14.396, 'epoch': 2.0}
{'loss': 1.9634, 'grad_norm': 3.904709815979004, 'learning_rate': 5.988955786831632e-09, 'epoch': 2.37}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.9618217945098877, 'eval_runtime': 3.6939, 'eval_samples_per_second': 228.483, 'eval_steps_per_second': 14.348, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.9606412649154663, 'eval_runtime': 3.6906, 'eval_samples_per_second': 228.688, 'eval_steps_per_second': 14.361, 'epoch': 4.0}
{'loss': 1.9579, 'grad_norm': 6.851970195770264, 'learning_rate': 5.935001230193509e-10, 'epoch': 4.74}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.960334062576294, 'eval_runtime': 3.702, 'eval_samples_per_second': 227.988, 'eval_steps_per_second': 14.317, 'epoch': 5.0}
{'train_runtime': 302.1291, 'train_samples_per_second': 55.837, 'train_steps_per_second': 3.492, 'train_loss': 1.9603391602141031, 'epoch': 5.0}

  0%|          | 0/53 [00:00<?, ?it/s]

[I 2024-06-02 15:21:31,163] Trial 2 finished with value: 1.960334062576294 and parameters: {'learning_rate': 1.1384411450643913e-08, 'batch_size': 16, 'num_train_epochs': 5}. Best is trial 1 with value: 1.0490789413452148.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1688 [00:00<?, ?it/s]

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 0.9204449653625488, 'eval_runtime': 3.813, 'eval_samples_per_second': 221.348, 'eval_steps_per_second': 27.8, 'epoch': 1.0}
{'loss': 1.0545, 'grad_norm': 11.033124923706055, 'learning_rate': 6.2575025274099175e-06, 'epoch': 1.18}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 0.7628334164619446, 'eval_runtime': 3.7922, 'eval_samples_per_second': 222.565, 'eval_steps_per_second': 27.952, 'epoch': 2.0}
{'loss': 0.757, 'grad_norm': 40.17641067504883, 'learning_rate': 3.6238735175572584e-06, 'epoch': 2.37}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 0.7697476148605347, 'eval_runtime': 3.8155, 'eval_samples_per_second': 221.203, 'eval_steps_per_second': 27.781, 'epoch': 3.0}
{'loss': 0.6094, 'grad_norm': 13.500922203063965, 'learning_rate': 9.902445077045997e-07, 'epoch': 3.55}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 0.7674949765205383, 'eval_runtime': 3.802, 'eval_samples_per_second': 221.988, 'eval_steps_per_second': 27.88, 'epoch': 4.0}
{'train_runtime': 264.6324, 'train_samples_per_second': 50.999, 'train_steps_per_second': 6.379, 'train_loss': 0.7818066384555039, 'epoch': 4.0}

  0%|          | 0/106 [00:00<?, ?it/s]

[I 2024-06-02 15:26:01,501] Trial 3 finished with value: 0.7628334164619446 and parameters: {'learning_rate': 8.891131537262577e-06, 'batch_size': 8, 'num_train_epochs': 4}. Best is trial 3 with value: 0.7628334164619446.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1688 [00:00<?, ?it/s]

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 2.0855910778045654, 'eval_runtime': 3.7951, 'eval_samples_per_second': 222.394, 'eval_steps_per_second': 27.931, 'epoch': 1.0}
{'loss': 2.1035, 'grad_norm': 8.134073257446289, 'learning_rate': 3.742514371084629e-08, 'epoch': 1.18}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 2.061231851577759, 'eval_runtime': 4.8101, 'eval_samples_per_second': 175.463, 'eval_steps_per_second': 22.037, 'epoch': 2.0}
{'loss': 2.065, 'grad_norm': 6.367833137512207, 'learning_rate': 2.1673820600220746e-08, 'epoch': 2.37}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 2.046201705932617, 'eval_runtime': 4.6741, 'eval_samples_per_second': 180.571, 'eval_steps_per_second': 22.678, 'epoch': 3.0}
{'loss': 2.0384, 'grad_norm': 6.048377990722656, 'learning_rate': 5.922497489595204e-09, 'epoch': 3.55}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 2.0411336421966553, 'eval_runtime': 4.7162, 'eval_samples_per_second': 178.956, 'eval_steps_per_second': 22.476, 'epoch': 4.0}
{'train_runtime': 288.9976, 'train_samples_per_second': 46.699, 'train_steps_per_second': 5.841, 'train_loss': 2.065302500792589, 'epoch': 4.0}

  0%|          | 0/106 [00:00<?, ?it/s]

[I 2024-06-02 15:30:56,966] Trial 4 finished with value: 2.0411336421966553 and parameters: {'learning_rate': 5.317646682147183e-08, 'batch_size': 8, 'num_train_epochs': 4}. Best is trial 3 with value: 0.7628334164619446.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1060 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 2.1144819259643555, 'eval_runtime': 4.77, 'eval_samples_per_second': 176.94, 'eval_steps_per_second': 5.66, 'epoch': 1.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 2.1101694107055664, 'eval_runtime': 4.7582, 'eval_samples_per_second': 177.379, 'eval_steps_per_second': 5.674, 'epoch': 2.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 2.106445074081421, 'eval_runtime': 4.7566, 'eval_samples_per_second': 177.438, 'eval_steps_per_second': 5.676, 'epoch': 3.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 2.1031887531280518, 'eval_runtime': 4.7795, 'eval_samples_per_second': 176.589, 'eval_steps_per_second': 5.649, 'epoch': 4.0}
{'loss': 2.1154, 'grad_norm': 6.225344657897949, 'learning_rate': 1.2041657195570666e-08, 'epoch': 4.72}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 2.100417375564575, 'eval_runtime': 3.6791, 'eval_samples_per_second': 229.406, 'eval_steps_per_second': 7.339, 'epoch': 5.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 2.0981760025024414, 'eval_runtime': 3.6771, 'eval_samples_per_second': 229.527, 'eval_steps_per_second': 7.343, 'epoch': 6.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 2.096405267715454, 'eval_runtime': 3.6813, 'eval_samples_per_second': 229.268, 'eval_steps_per_second': 7.334, 'epoch': 7.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 2.095150947570801, 'eval_runtime': 3.6824, 'eval_samples_per_second': 229.198, 'eval_steps_per_second': 7.332, 'epoch': 8.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 2.094402313232422, 'eval_runtime': 3.6936, 'eval_samples_per_second': 228.501, 'eval_steps_per_second': 7.31, 'epoch': 9.0}
{'loss': 2.0999, 'grad_norm': 5.669088363647461, 'learning_rate': 1.2901775566682855e-09, 'epoch': 9.43}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 2.094210147857666, 'eval_runtime': 3.6875, 'eval_samples_per_second': 228.884, 'eval_steps_per_second': 7.322, 'epoch': 10.0}
{'train_runtime': 638.6684, 'train_samples_per_second': 52.829, 'train_steps_per_second': 1.66, 'train_loss': 2.10700679994979, 'epoch': 10.0}

  0%|          | 0/27 [00:00<?, ?it/s]

[I 2024-06-02 15:41:41,157] Trial 5 finished with value: 2.094210147857666 and parameters: {'learning_rate': 2.2793136834473045e-08, 'batch_size': 32, 'num_train_epochs': 10}. Best is trial 3 with value: 0.7628334164619446.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1266 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8705477714538574, 'eval_runtime': 3.7022, 'eval_samples_per_second': 227.973, 'eval_steps_per_second': 14.316, 'epoch': 1.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7696851491928101, 'eval_runtime': 3.6986, 'eval_samples_per_second': 228.194, 'eval_steps_per_second': 14.33, 'epoch': 2.0}
{'loss': 0.9171, 'grad_norm': 17.024993896484375, 'learning_rate': 8.832154562252292e-06, 'epoch': 2.37}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7726161479949951, 'eval_runtime': 3.6924, 'eval_samples_per_second': 228.579, 'eval_steps_per_second': 14.354, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7906789183616638, 'eval_runtime': 3.7028, 'eval_samples_per_second': 227.938, 'eval_steps_per_second': 14.314, 'epoch': 4.0}
{'loss': 0.523, 'grad_norm': 23.989084243774414, 'learning_rate': 3.067040618223381e-06, 'epoch': 4.74}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8118649125099182, 'eval_runtime': 3.6844, 'eval_samples_per_second': 229.073, 'eval_steps_per_second': 14.385, 'epoch': 5.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8406664133071899, 'eval_runtime': 3.703, 'eval_samples_per_second': 227.926, 'eval_steps_per_second': 14.313, 'epoch': 6.0}
{'train_runtime': 362.0366, 'train_samples_per_second': 55.917, 'train_steps_per_second': 3.497, 'train_loss': 0.6490051426217077, 'epoch': 6.0}

  0%|          | 0/53 [00:00<?, ?it/s]

[I 2024-06-02 15:47:48,757] Trial 6 finished with value: 0.7696851491928101 and parameters: {'learning_rate': 1.4597268506281204e-05, 'batch_size': 16, 'num_train_epochs': 6}. Best is trial 3 with value: 0.7628334164619446.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/633 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.9630820751190186, 'eval_runtime': 3.6867, 'eval_samples_per_second': 228.933, 'eval_steps_per_second': 14.376, 'epoch': 1.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.9586786031723022, 'eval_runtime': 3.7044, 'eval_samples_per_second': 227.837, 'eval_steps_per_second': 14.307, 'epoch': 2.0}
{'loss': 1.959, 'grad_norm': 3.816117286682129, 'learning_rate': 5.097673908057814e-09, 'epoch': 2.37}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.9572259187698364, 'eval_runtime': 3.7017, 'eval_samples_per_second': 228.001, 'eval_steps_per_second': 14.318, 'epoch': 3.0}
{'train_runtime': 181.0147, 'train_samples_per_second': 55.918, 'train_steps_per_second': 3.497, 'train_loss': 1.9565936867471367, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

[I 2024-06-02 15:50:55,326] Trial 7 finished with value: 1.9572259187698364 and parameters: {'learning_rate': 2.426186153233531e-08, 'batch_size': 16, 'num_train_epochs': 3}. Best is trial 3 with value: 0.7628334164619446.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/318 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 1.6773995161056519, 'eval_runtime': 3.6728, 'eval_samples_per_second': 229.8, 'eval_steps_per_second': 7.351, 'epoch': 1.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 1.2269536256790161, 'eval_runtime': 3.6821, 'eval_samples_per_second': 229.218, 'eval_steps_per_second': 7.333, 'epoch': 2.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 1.2047252655029297, 'eval_runtime': 3.6834, 'eval_samples_per_second': 229.138, 'eval_steps_per_second': 7.33, 'epoch': 3.0}
{'train_runtime': 177.2908, 'train_samples_per_second': 57.093, 'train_steps_per_second': 1.794, 'train_loss': 1.4956823384986733, 'epoch': 3.0}

  0%|          | 0/27 [00:00<?, ?it/s]

[I 2024-06-02 15:53:57,686] Trial 8 finished with value: 1.2047252655029297 and parameters: {'learning_rate': 1.0403448244143554e-06, 'batch_size': 32, 'num_train_epochs': 3}. Best is trial 3 with value: 0.7628334164619446.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/318 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 1.9047901630401611, 'eval_runtime': 3.6902, 'eval_samples_per_second': 228.714, 'eval_steps_per_second': 7.317, 'epoch': 1.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 1.8543810844421387, 'eval_runtime': 3.6809, 'eval_samples_per_second': 229.291, 'eval_steps_per_second': 7.335, 'epoch': 2.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 1.8329858779907227, 'eval_runtime': 3.6862, 'eval_samples_per_second': 228.963, 'eval_steps_per_second': 7.325, 'epoch': 3.0}
{'train_runtime': 176.7739, 'train_samples_per_second': 57.26, 'train_steps_per_second': 1.799, 'train_loss': 1.8767990016337461, 'epoch': 3.0}

  0%|          | 0/27 [00:00<?, ?it/s]

[I 2024-06-02 15:56:59,917] Trial 9 finished with value: 1.8329858779907227 and parameters: {'learning_rate': 3.6658262006641656e-07, 'batch_size': 32, 'num_train_epochs': 3}. Best is trial 3 with value: 0.7628334164619446.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/3798 [00:00<?, ?it/s]

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.2382581233978271, 'eval_runtime': 3.8143, 'eval_samples_per_second': 221.272, 'eval_steps_per_second': 27.79, 'epoch': 1.0}
{'loss': 1.2282, 'grad_norm': 1.9360878467559814, 'learning_rate': 8.633409638119823e-05, 'epoch': 1.18}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.2022076845169067, 'eval_runtime': 3.8025, 'eval_samples_per_second': 221.956, 'eval_steps_per_second': 27.876, 'epoch': 2.0}
{'loss': 1.2204, 'grad_norm': 1.8678644895553589, 'learning_rate': 7.324524004687465e-05, 'epoch': 2.37}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.1966265439987183, 'eval_runtime': 3.8117, 'eval_samples_per_second': 221.423, 'eval_steps_per_second': 27.809, 'epoch': 3.0}
{'loss': 1.186, 'grad_norm': 2.280574321746826, 'learning_rate': 6.01563837125511e-05, 'epoch': 3.55}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.1894339323043823, 'eval_runtime': 3.8167, 'eval_samples_per_second': 221.133, 'eval_steps_per_second': 27.773, 'epoch': 4.0}
{'loss': 1.2065, 'grad_norm': 2.433891534805298, 'learning_rate': 4.7067527378227536e-05, 'epoch': 4.74}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.1963437795639038, 'eval_runtime': 3.826, 'eval_samples_per_second': 220.596, 'eval_steps_per_second': 27.705, 'epoch': 5.0}
{'loss': 1.192, 'grad_norm': 4.626056671142578, 'learning_rate': 3.397867104390397e-05, 'epoch': 5.92}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.1885390281677246, 'eval_runtime': 3.8103, 'eval_samples_per_second': 221.505, 'eval_steps_per_second': 27.819, 'epoch': 6.0}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.1853306293487549, 'eval_runtime': 3.7983, 'eval_samples_per_second': 222.205, 'eval_steps_per_second': 27.907, 'epoch': 7.0}
{'loss': 1.2019, 'grad_norm': 3.6660938262939453, 'learning_rate': 2.0889814709580407e-05, 'epoch': 7.11}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.1848576068878174, 'eval_runtime': 3.8093, 'eval_samples_per_second': 221.564, 'eval_steps_per_second': 27.827, 'epoch': 8.0}
{'loss': 1.1966, 'grad_norm': 6.369298934936523, 'learning_rate': 7.800958375256845e-06, 'epoch': 8.29}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.1866799592971802, 'eval_runtime': 3.8081, 'eval_samples_per_second': 221.632, 'eval_steps_per_second': 27.835, 'epoch': 9.0}
{'train_runtime': 598.5205, 'train_samples_per_second': 50.735, 'train_steps_per_second': 6.346, 'train_loss': 1.2018126637889186, 'epoch': 9.0}

  0%|          | 0/106 [00:00<?, ?it/s]

[I 2024-06-02 16:07:04,015] Trial 10 finished with value: 1.1848576068878174 and parameters: {'learning_rate': 9.942295271552179e-05, 'batch_size': 8, 'num_train_epochs': 9}. Best is trial 3 with value: 0.7628334164619446.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/3376 [00:00<?, ?it/s]

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 0.8822894096374512, 'eval_runtime': 3.8006, 'eval_samples_per_second': 222.067, 'eval_steps_per_second': 27.89, 'epoch': 1.0}
{'loss': 1.0087, 'grad_norm': 13.83307933807373, 'learning_rate': 1.9173048801917457e-05, 'epoch': 1.18}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 0.7972250580787659, 'eval_runtime': 3.8135, 'eval_samples_per_second': 221.32, 'eval_steps_per_second': 27.796, 'epoch': 2.0}
{'loss': 0.7197, 'grad_norm': 31.609582901000977, 'learning_rate': 1.5839764935102878e-05, 'epoch': 2.37}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 0.8531162738800049, 'eval_runtime': 3.8035, 'eval_samples_per_second': 221.904, 'eval_steps_per_second': 27.869, 'epoch': 3.0}
{'loss': 0.5155, 'grad_norm': 8.73058795928955, 'learning_rate': 1.25064810682883e-05, 'epoch': 3.55}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.1694327592849731, 'eval_runtime': 3.8137, 'eval_samples_per_second': 221.307, 'eval_steps_per_second': 27.795, 'epoch': 4.0}
{'loss': 0.3944, 'grad_norm': 0.23465286195278168, 'learning_rate': 9.173197201473721e-06, 'epoch': 4.74}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.2889097929000854, 'eval_runtime': 3.8075, 'eval_samples_per_second': 221.67, 'eval_steps_per_second': 27.84, 'epoch': 5.0}
{'loss': 0.2683, 'grad_norm': 56.06507873535156, 'learning_rate': 5.839913334659142e-06, 'epoch': 5.92}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.431788444519043, 'eval_runtime': 3.8033, 'eval_samples_per_second': 221.911, 'eval_steps_per_second': 27.87, 'epoch': 6.0}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.5584615468978882, 'eval_runtime': 3.8051, 'eval_samples_per_second': 221.809, 'eval_steps_per_second': 27.858, 'epoch': 7.0}
{'loss': 0.1726, 'grad_norm': 37.15769577026367, 'learning_rate': 2.506629467844563e-06, 'epoch': 7.11}

  0%|          | 0/106 [00:00<?, ?it/s]

{'eval_loss': 1.608083724975586, 'eval_runtime': 3.7989, 'eval_samples_per_second': 222.171, 'eval_steps_per_second': 27.903, 'epoch': 8.0}
{'train_runtime': 537.0634, 'train_samples_per_second': 50.258, 'train_steps_per_second': 6.286, 'train_loss': 0.4698878487139517, 'epoch': 8.0}

  0%|          | 0/106 [00:00<?, ?it/s]

[I 2024-06-02 16:16:06,762] Trial 11 finished with value: 0.7972250580787659 and parameters: {'learning_rate': 2.2506332668732037e-05, 'batch_size': 8, 'num_train_epochs': 8}. Best is trial 3 with value: 0.7628334164619446.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1477 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.9347343444824219, 'eval_runtime': 3.6922, 'eval_samples_per_second': 228.589, 'eval_steps_per_second': 14.355, 'epoch': 1.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8134294152259827, 'eval_runtime': 3.6953, 'eval_samples_per_second': 228.397, 'eval_steps_per_second': 14.342, 'epoch': 2.0}
{'loss': 1.0135, 'grad_norm': 23.69084358215332, 'learning_rate': 4.1208904341284666e-06, 'epoch': 2.37}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7786051630973816, 'eval_runtime': 3.6901, 'eval_samples_per_second': 228.718, 'eval_steps_per_second': 14.363, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7454573512077332, 'eval_runtime': 3.6955, 'eval_samples_per_second': 228.384, 'eval_steps_per_second': 14.342, 'epoch': 4.0}
{'loss': 0.6763, 'grad_norm': 20.521148681640625, 'learning_rate': 2.0119393419439907e-06, 'epoch': 4.74}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7455782294273376, 'eval_runtime': 3.6958, 'eval_samples_per_second': 228.368, 'eval_steps_per_second': 14.341, 'epoch': 5.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7696103453636169, 'eval_runtime': 3.6932, 'eval_samples_per_second': 228.53, 'eval_steps_per_second': 14.351, 'epoch': 6.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7657212615013123, 'eval_runtime': 3.7034, 'eval_samples_per_second': 227.896, 'eval_steps_per_second': 14.311, 'epoch': 7.0}
{'train_runtime': 422.703, 'train_samples_per_second': 55.874, 'train_steps_per_second': 3.494, 'train_loss': 0.7543794067630755, 'epoch': 7.0}

  0%|          | 0/53 [00:00<?, ?it/s]

[I 2024-06-02 16:23:15,055] Trial 12 finished with value: 0.7454573512077332 and parameters: {'learning_rate': 6.229841526312943e-06, 'batch_size': 16, 'num_train_epochs': 7}. Best is trial 12 with value: 0.7454573512077332.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1688 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.0505598783493042, 'eval_runtime': 3.6941, 'eval_samples_per_second': 228.472, 'eval_steps_per_second': 14.347, 'epoch': 1.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.866554856300354, 'eval_runtime': 3.6989, 'eval_samples_per_second': 228.173, 'eval_steps_per_second': 14.328, 'epoch': 2.0}
{'loss': 1.0763, 'grad_norm': 13.385263442993164, 'learning_rate': 3.6230892305614306e-06, 'epoch': 2.37}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8121548891067505, 'eval_runtime': 3.6896, 'eval_samples_per_second': 228.752, 'eval_steps_per_second': 14.365, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.764778196811676, 'eval_runtime': 3.6971, 'eval_samples_per_second': 228.286, 'eval_steps_per_second': 14.335, 'epoch': 4.0}
{'loss': 0.7308, 'grad_norm': 15.740436553955078, 'learning_rate': 2.098220025779684e-06, 'epoch': 4.74}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7548196911811829, 'eval_runtime': 3.6978, 'eval_samples_per_second': 228.246, 'eval_steps_per_second': 14.333, 'epoch': 5.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7804439663887024, 'eval_runtime': 3.7062, 'eval_samples_per_second': 227.725, 'eval_steps_per_second': 14.3, 'epoch': 6.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7700220346450806, 'eval_runtime': 3.6967, 'eval_samples_per_second': 228.312, 'eval_steps_per_second': 14.337, 'epoch': 7.0}
{'loss': 0.6075, 'grad_norm': 17.847217559814453, 'learning_rate': 5.733508209979368e-07, 'epoch': 7.11}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7768744230270386, 'eval_runtime': 3.7048, 'eval_samples_per_second': 227.812, 'eval_steps_per_second': 14.306, 'epoch': 8.0}
{'train_runtime': 483.1878, 'train_samples_per_second': 55.862, 'train_steps_per_second': 3.493, 'train_loss': 0.7774947017290016, 'epoch': 8.0}

  0%|          | 0/53 [00:00<?, ?it/s]

[I 2024-06-02 16:31:23,451] Trial 13 finished with value: 0.7548196911811829 and parameters: {'learning_rate': 5.147958435343178e-06, 'batch_size': 16, 'num_train_epochs': 8}. Best is trial 12 with value: 0.7454573512077332.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1688 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.0939383506774902, 'eval_runtime': 3.6957, 'eval_samples_per_second': 228.372, 'eval_steps_per_second': 14.341, 'epoch': 1.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.9184727072715759, 'eval_runtime': 3.7128, 'eval_samples_per_second': 227.322, 'eval_steps_per_second': 14.275, 'epoch': 2.0}
{'loss': 1.1404, 'grad_norm': 17.229644775390625, 'learning_rate': 2.4594876332668648e-06, 'epoch': 2.37}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8350130915641785, 'eval_runtime': 3.6953, 'eval_samples_per_second': 228.398, 'eval_steps_per_second': 14.343, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7929894328117371, 'eval_runtime': 3.682, 'eval_samples_per_second': 229.22, 'eval_steps_per_second': 14.394, 'epoch': 4.0}
{'loss': 0.8061, 'grad_norm': 13.978602409362793, 'learning_rate': 1.4243497404777802e-06, 'epoch': 4.74}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7749387621879578, 'eval_runtime': 3.6916, 'eval_samples_per_second': 228.624, 'eval_steps_per_second': 14.357, 'epoch': 5.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7727923393249512, 'eval_runtime': 3.7128, 'eval_samples_per_second': 227.322, 'eval_steps_per_second': 14.275, 'epoch': 6.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7600833177566528, 'eval_runtime': 3.7044, 'eval_samples_per_second': 227.835, 'eval_steps_per_second': 14.307, 'epoch': 7.0}
{'loss': 0.7023, 'grad_norm': 15.219218254089355, 'learning_rate': 3.892118476886958e-07, 'epoch': 7.11}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7645971179008484, 'eval_runtime': 3.6937, 'eval_samples_per_second': 228.499, 'eval_steps_per_second': 14.349, 'epoch': 8.0}
{'train_runtime': 483.4568, 'train_samples_per_second': 55.831, 'train_steps_per_second': 3.492, 'train_loss': 0.8579382421846073, 'epoch': 8.0}

  0%|          | 0/53 [00:00<?, ?it/s]

[I 2024-06-02 16:39:32,521] Trial 14 finished with value: 0.7600833177566528 and parameters: {'learning_rate': 3.4946255260559495e-06, 'batch_size': 16, 'num_train_epochs': 8}. Best is trial 12 with value: 0.7454573512077332.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1477 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.1058640480041504, 'eval_runtime': 3.6885, 'eval_samples_per_second': 228.82, 'eval_steps_per_second': 14.369, 'epoch': 1.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.9375263452529907, 'eval_runtime': 3.7037, 'eval_samples_per_second': 227.88, 'eval_steps_per_second': 14.31, 'epoch': 2.0}
{'loss': 1.1548, 'grad_norm': 15.638358116149902, 'learning_rate': 2.122153578265394e-06, 'epoch': 2.37}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8531543612480164, 'eval_runtime': 3.6917, 'eval_samples_per_second': 228.621, 'eval_steps_per_second': 14.357, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8100312352180481, 'eval_runtime': 3.7077, 'eval_samples_per_second': 227.632, 'eval_steps_per_second': 14.294, 'epoch': 4.0}
{'loss': 0.8313, 'grad_norm': 12.33405876159668, 'learning_rate': 1.0360974993168814e-06, 'epoch': 4.74}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7929556369781494, 'eval_runtime': 3.6882, 'eval_samples_per_second': 228.839, 'eval_steps_per_second': 14.37, 'epoch': 5.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.78143310546875, 'eval_runtime': 3.6998, 'eval_samples_per_second': 228.119, 'eval_steps_per_second': 14.325, 'epoch': 6.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7806074619293213, 'eval_runtime': 3.6953, 'eval_samples_per_second': 228.401, 'eval_steps_per_second': 14.343, 'epoch': 7.0}
{'train_runtime': 423.0991, 'train_samples_per_second': 55.821, 'train_steps_per_second': 3.491, 'train_loss': 0.9128690705399458, 'epoch': 7.0}

  0%|          | 0/53 [00:00<?, ?it/s]

[I 2024-06-02 16:46:41,268] Trial 15 finished with value: 0.7806074619293213 and parameters: {'learning_rate': 3.208209657213907e-06, 'batch_size': 16, 'num_train_epochs': 7}. Best is trial 12 with value: 0.7454573512077332.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1688 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.9216710925102234, 'eval_runtime': 3.7031, 'eval_samples_per_second': 227.918, 'eval_steps_per_second': 14.312, 'epoch': 1.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8211525082588196, 'eval_runtime': 3.6835, 'eval_samples_per_second': 229.132, 'eval_steps_per_second': 14.389, 'epoch': 2.0}
{'loss': 0.8886, 'grad_norm': 8.848426818847656, 'learning_rate': 3.81047334574779e-05, 'epoch': 2.37}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8088403940200806, 'eval_runtime': 3.6956, 'eval_samples_per_second': 228.38, 'eval_steps_per_second': 14.341, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.9672375917434692, 'eval_runtime': 3.7024, 'eval_samples_per_second': 227.963, 'eval_steps_per_second': 14.315, 'epoch': 4.0}
{'loss': 0.4768, 'grad_norm': 5.751553058624268, 'learning_rate': 2.2067387726216158e-05, 'epoch': 4.74}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.1180570125579834, 'eval_runtime': 3.6941, 'eval_samples_per_second': 228.473, 'eval_steps_per_second': 14.347, 'epoch': 5.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.2337511777877808, 'eval_runtime': 3.6954, 'eval_samples_per_second': 228.389, 'eval_steps_per_second': 14.342, 'epoch': 6.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.4621739387512207, 'eval_runtime': 3.6973, 'eval_samples_per_second': 228.276, 'eval_steps_per_second': 14.335, 'epoch': 7.0}
{'loss': 0.1976, 'grad_norm': 43.84260940551758, 'learning_rate': 6.030041994954415e-06, 'epoch': 7.11}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.5254014730453491, 'eval_runtime': 3.7125, 'eval_samples_per_second': 227.338, 'eval_steps_per_second': 14.276, 'epoch': 8.0}
{'train_runtime': 486.902, 'train_samples_per_second': 55.436, 'train_steps_per_second': 3.467, 'train_loss': 0.47105476528547385, 'epoch': 8.0}

  0%|          | 0/53 [00:00<?, ?it/s]

[I 2024-06-02 16:54:53,727] Trial 16 finished with value: 0.8088403940200806 and parameters: {'learning_rate': 5.414207918873964e-05, 'batch_size': 16, 'num_train_epochs': 8}. Best is trial 12 with value: 0.7454573512077332.
/tmp/ipykernel_3223573/1514148416.py:54: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-8, 1e-4)
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/2110 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.9743397235870361, 'eval_runtime': 3.6985, 'eval_samples_per_second': 228.199, 'eval_steps_per_second': 14.33, 'epoch': 1.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.9064236879348755, 'eval_runtime': 3.6957, 'eval_samples_per_second': 228.372, 'eval_steps_per_second': 14.341, 'epoch': 2.0}
{'loss': 1.9491, 'grad_norm': 3.8310048580169678, 'learning_rate': 1.2574894111877508e-07, 'epoch': 2.37}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.8074918985366821, 'eval_runtime': 4.7329, 'eval_samples_per_second': 178.325, 'eval_steps_per_second': 11.198, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.6054861545562744, 'eval_runtime': 4.7358, 'eval_samples_per_second': 178.215, 'eval_steps_per_second': 11.191, 'epoch': 4.0}
{'loss': 1.6675, 'grad_norm': 16.90633773803711, 'learning_rate': 8.669647493282008e-08, 'epoch': 4.74}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 1.327257752418518, 'eval_runtime': 4.5711, 'eval_samples_per_second': 184.637, 'eval_steps_per_second': 11.594, 'epoch': 5.0}

[W 2024-06-02 17:00:41,124] Trial 17 failed with parameters: {'learning_rate': 1.6480140730473007e-07, 'batch_size': 16, 'num_train_epochs': 10} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_3223573/1514148416.py", line 89, in objective
    trainer.train()
  File "/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/trainer.py", line 2218, in _inner_training_loop
    if (
KeyboardInterrupt
[W 2024-06-02 17:00:41,126] Trial 17 failed with value None.

KeyboardInterrupt:

In [12]:
# clear memory with torch
import torch
torch.cuda.empty_cache()
gc.collect()

0

In [2]:
import ast
from transformers import TrainingArguments, Trainer, AutoModelForSequenceClassification
from sklearn.metrics import balanced_accuracy_score

# Load best hyperparameters from a text file
with open("best_hyperparameters.txt", "r") as f:
    best_hyperparameters = ast.literal_eval(f.read())

# Load the model
model_name = "roberta-base"
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)

# Define training arguments with the best hyperparameters
training_args = TrainingArguments(
    output_dir="./roberta-best-param",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=best_hyperparameters['learning_rate'],
    per_device_train_batch_size=best_hyperparameters['batch_size'],
    per_device_eval_batch_size=best_hyperparameters['batch_size'],
    num_train_epochs=best_hyperparameters['num_train_epochs'],
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer with the best hyperparameters
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)

# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1477 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.9475564956665039, 'eval_runtime': 4.654, 'eval_samples_per_second': 181.35, 'eval_steps_per_second': 11.388, 'epoch': 1.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8482066988945007, 'eval_runtime': 4.7395, 'eval_samples_per_second': 178.078, 'eval_steps_per_second': 11.183, 'epoch': 2.0}
{'loss': 0.991, 'grad_norm': 23.51766014099121, 'learning_rate': 4.1208904341284666e-06, 'epoch': 2.37}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8097977638244629, 'eval_runtime': 4.5784, 'eval_samples_per_second': 184.343, 'eval_steps_per_second': 11.576, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7992478609085083, 'eval_runtime': 4.6584, 'eval_samples_per_second': 181.18, 'eval_steps_per_second': 11.377, 'epoch': 4.0}
{'loss': 0.6696, 'grad_norm': 12.831771850585938, 'learning_rate': 2.0119393419439907e-06, 'epoch': 4.74}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8044332265853882, 'eval_runtime': 4.6024, 'eval_samples_per_second': 183.384, 'eval_steps_per_second': 11.516, 'epoch': 5.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.7978417277336121, 'eval_runtime': 4.7975, 'eval_samples_per_second': 175.924, 'eval_steps_per_second': 11.047, 'epoch': 6.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8045294284820557, 'eval_runtime': 4.4659, 'eval_samples_per_second': 188.989, 'eval_steps_per_second': 11.868, 'epoch': 7.0}
{'train_runtime': 492.1352, 'train_samples_per_second': 47.991, 'train_steps_per_second': 3.001, 'train_loss': 0.7444559457581351, 'epoch': 7.0}

  0%|          | 0/53 [00:00<?, ?it/s]

Balanced Accuracy: 0.41636881143284843

In [12]:
import pandas as pd
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import balanced_accuracy_score
import nlpaug.augmenter.word as naw
import ast

# Load the CSV file
file_path = f'{DATA_DIR}/train_eng_v2.csv'
df = pd.read_csv(file_path)

# Create a label mapping
label_mapping = {
    'Politik': 0,
    'Sosial Budaya': 1,
    'Ekonomi': 2,
    'Pertahanan dan Keamanan': 3,
    'Ideologi': 4,
    'Sumber Daya Alam': 5,
    'Demografi': 6,
    'Geografi': 7
}

# Apply the label mapping
df['label'] = df['label'].map(label_mapping)

# Split the DataFrame into training and validation sets
train_df, val_df = train_test_split(df, test_size=0.2, stratify=df['label'])

# Create an augmenter using BERT
aug = naw.ContextualWordEmbsAug(model_path='bert-base-uncased', action="substitute")

# Function to augment data
def augment_data(df, target_count):
    augmented_texts = []
    augmented_labels = []
    
    for label in df['label'].unique():
        subset = df[df['label'] == label]
        current_count = len(subset)
        
        while current_count < target_count:
            for text in subset['text']:
                augmented_text = aug.augment(text)[0]  # Take the string out of the list
                augmented_texts.append(augmented_text)
                augmented_labels.append(label)
                current_count += 1
                if current_count >= target_count:
                    break

    augmented_df = pd.DataFrame({'text': augmented_texts, 'label': augmented_labels})
    return pd.concat([df, augmented_df], ignore_index=True)

# Augment the training data to ensure each class has at least 305 examples
train_df_augmented = augment_data(train_df, 305)

In [13]:
train_df_augmented['label'].value_counts()

label
0    2286
3     305
4     305
2     305
1     305
6     305
5     305
7     305
Name: count, dtype: int64

In [15]:
train_df_augmented.to_csv(f"{DATA_DIR}/trainaug.csv", index=False)

In [16]:
val_df.to_csv(f"{DATA_DIR}/val.csv", index=False)

## AUGMENTATION BELOW

In [4]:
import re
from nltk.corpus import stopwords
import pandas as pd


def preprocess_text(text):
    # Define stopwords
    stop_words = set(stopwords.words('english'))
    # Add custom words to remove
    custom_words = {'anies', 'prabowo', 'gibran', 'ganjar'}
    all_stopwords = stop_words.union(custom_words)

    # Remove hashtags
    text = re.sub(r'#\w+', '', text)
    # Remove URLs
    text = re.sub(r'http\S+', '', text)
    # Remove stopwords and custom words
    text = ' '.join([word for word in text.split() if word.lower() not in all_stopwords])

    return text

train_df_augmented = pd.read_csv(f"{DATA_DIR}/trainaug.csv")
val_df = pd.read_csv(f"{DATA_DIR}/val.csv")

In [5]:
# Convert DataFrames to Datasets
train_dataset = Dataset.from_pandas(train_df_augmented)
val_dataset = Dataset.from_pandas(val_df)

# Combine into a DatasetDict
dataset = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset
})

# Tokenize the dataset
model_name = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Load the model
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)

# Define training arguments
training_args = TrainingArguments(
    output_dir="./xlmroberta3augnostop",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)

# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

Map:   0%|          | 0/4421 [00:00<?, ? examples/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/831 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.9604026675224304, 'eval_runtime': 4.6786, 'eval_samples_per_second': 180.396, 'eval_steps_per_second': 11.328, 'epoch': 1.0}
{'loss': 1.1769, 'grad_norm': 8.031410217285156, 'learning_rate': 7.966305655836343e-06, 'epoch': 1.81}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8297074437141418, 'eval_runtime': 4.6986, 'eval_samples_per_second': 179.628, 'eval_steps_per_second': 11.28, 'epoch': 2.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8164283037185669, 'eval_runtime': 4.337, 'eval_samples_per_second': 194.606, 'eval_steps_per_second': 12.221, 'epoch': 3.0}
{'train_runtime': 330.0393, 'train_samples_per_second': 40.186, 'train_steps_per_second': 2.518, 'train_loss': 1.0019352037266847, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

Balanced Accuracy: 0.3866808154200817

In [6]:
train_df_augmented

                                                   text  label
0     Law No. 16 of 2012 concerning the Defense Indu...      3
1     Ideally the second round would be Ganjar - Mah...      0
2     KN 02 Prabowo Gibran row of KPK patients. Khof...      0
3     JK on Purchasing Used Defense Equipment from t...      3
4     Nobar with my mother for treatment, the commen...      0
...                                                 ...    ...
4416  so no want to move to ikn later if i wish my l...      7
4417  my village lives in ruins, near north high hil...      7
4418  remember my supporters ; lift your spirits up,...      7
4419  new year's eve, reward salawat & wednesday ; i...      7
4420  he's just a working island, because it was alr...      7

[4421 rows x 2 columns]

In [17]:
import pandas as pd
from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import train_test_split

train_df_augmented = pd.read_csv(f"{DATA_DIR}/trainaug.csv")
val_df = pd.read_csv(f"{DATA_DIR}/val.csv")

# Convert DataFrames to Datasets
train_dataset = Dataset.from_pandas(train_df_augmented)
val_dataset = Dataset.from_pandas(val_df)

# Combine into a DatasetDict
dataset = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset
})

# Tokenize the dataset
model_name = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Load the model
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)


training_args = TrainingArguments(
    output_dir="./roberta3aug",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=5,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)


# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

Map:   0%|          | 0/4421 [00:00<?, ? examples/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/417 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.9378998875617981, 'eval_runtime': 4.2583, 'eval_samples_per_second': 198.201, 'eval_steps_per_second': 6.341, 'epoch': 1.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8069957494735718, 'eval_runtime': 4.147, 'eval_samples_per_second': 203.523, 'eval_steps_per_second': 6.511, 'epoch': 2.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8015658259391785, 'eval_runtime': 4.335, 'eval_samples_per_second': 194.694, 'eval_steps_per_second': 6.228, 'epoch': 3.0}
{'train_runtime': 241.9996, 'train_samples_per_second': 54.806, 'train_steps_per_second': 1.723, 'train_loss': 0.9027446499831385, 'epoch': 3.0}

  0%|          | 0/27 [00:00<?, ?it/s]

Balanced Accuracy: 0.4242008959587381

In [1]:
import pandas as pd
from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import train_test_split
import nltk
import re
from nltk.corpus import stopwords

# Download NLTK stopwords
nltk.download('stopwords')

def preprocess_text(text):
    # Define stopwords
    stop_words = set(stopwords.words('english'))
    # Add custom words to remove
    custom_words = {'imin','anies', 'prabowo', 'gibran', 'ganjar', 'jokowi', 'sandiaga', 'ahok','mahfud', 'machfud'}
    all_stopwords = stop_words.union(custom_words)

    # Remove stopwords and custom words
    text = ' '.join([word for word in text.split() if word.lower() not in all_stopwords])

    return text

# Load the CSV files
train_df_augmented = pd.read_csv(f"{DATA_DIR}/trainaug.csv")
val_df = pd.read_csv(f"{DATA_DIR}/val.csv")

# Apply preprocessing to the text column
train_df_augmented['text'] = train_df_augmented['text'].apply(preprocess_text)
val_df['text'] = val_df['text'].apply(preprocess_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/ikhlasul.hanif/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [8]:
train_df_augmented

                                                   text  label
0     Law No. 16 2012 concerning Defense Industry in...      3
1     Ideally second round would - vs - Cak think on...      0
2     KN 02 row KPK patients. Khofifah grant funds. ...      0
3     JK Purchasing Used Defense Equipment Era: 25 Y...      3
4     Nobar mother treatment, comment "Why mean teas...      0
...                                                 ...    ...
4416  want move ikn later wish luck. hopefully futur...      7
4417  village lives ruins, near north high hill. far...      7
4418  remember supporters ; lift spirits up, soon ev...      7
4419  new year's eve, reward salawat & wednesday ; i...      7
4420  he's working island, already built came up. fo...      7

[4421 rows x 2 columns]

In [2]:
# Convert DataFrames to Datasets
train_dataset = Dataset.from_pandas(train_df_augmented)
val_dataset = Dataset.from_pandas(val_df)

# Combine into a DatasetDict
dataset = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset
})

# Tokenize the dataset
model_name = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Load the model
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)

# Define training arguments
training_args = TrainingArguments(
    output_dir="./roberta3augnostop",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)

# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

Map:   0%|          | 0/4421 [00:00<?, ? examples/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/417 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 1.0120782852172852, 'eval_runtime': 4.6832, 'eval_samples_per_second': 180.22, 'eval_steps_per_second': 5.765, 'epoch': 1.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.85716712474823, 'eval_runtime': 4.7003, 'eval_samples_per_second': 179.565, 'eval_steps_per_second': 5.744, 'epoch': 2.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8400566577911377, 'eval_runtime': 4.7073, 'eval_samples_per_second': 179.294, 'eval_steps_per_second': 5.736, 'epoch': 3.0}
{'train_runtime': 256.9132, 'train_samples_per_second': 51.624, 'train_steps_per_second': 1.623, 'train_loss': 1.0063824916629196, 'epoch': 3.0}

  0%|          | 0/27 [00:00<?, ?it/s]

Balanced Accuracy: 0.3929186703859582

In [3]:
# Convert DataFrames to Datasets
train_dataset = Dataset.from_pandas(train_df_augmented)
val_dataset = Dataset.from_pandas(val_df)

# Combine into a DatasetDict
dataset = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset
})

# Tokenize the dataset
model_name = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Load the model
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)

# Define training arguments
training_args = TrainingArguments(
    output_dir="./xlmroberta3augnostop",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)

# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

Map:   0%|          | 0/4421 [00:00<?, ? examples/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/831 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.9731300473213196, 'eval_runtime': 4.6774, 'eval_samples_per_second': 180.443, 'eval_steps_per_second': 11.331, 'epoch': 1.0}
{'loss': 1.2066, 'grad_norm': 9.956094741821289, 'learning_rate': 7.966305655836343e-06, 'epoch': 1.81}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8452609777450562, 'eval_runtime': 4.6809, 'eval_samples_per_second': 180.307, 'eval_steps_per_second': 11.323, 'epoch': 2.0}

  0%|          | 0/53 [00:00<?, ?it/s]

{'eval_loss': 0.8412941098213196, 'eval_runtime': 4.6846, 'eval_samples_per_second': 180.165, 'eval_steps_per_second': 11.314, 'epoch': 3.0}
{'train_runtime': 331.0804, 'train_samples_per_second': 40.06, 'train_steps_per_second': 2.51, 'train_loss': 1.0283804295582317, 'epoch': 3.0}

  0%|          | 0/53 [00:00<?, ?it/s]

Balanced Accuracy: 0.38996600275515514

In [ ]:
import pandas as pd
from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import train_test_split

# Convert DataFrames to Datasets
train_dataset = Dataset.from_pandas(train_df_augmented)
val_dataset = Dataset.from_pandas(val_df)

# Combine into a DatasetDict
dataset = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset
})

# Tokenize the dataset
model_name = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Load the model
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)


training_args = TrainingArguments(
    output_dir="./roberta3aug",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=1e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=5,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)


# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

In [18]:
# Convert DataFrames to Datasets
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

# Combine into a DatasetDict
dataset = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset
})

# Tokenize the dataset
model_name = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Load the model
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=8, ignore_mismatched_sizes=True)


training_args = TrainingArguments(
    output_dir="./roberta3aug",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)


# Train the model
trainer.train()

# Make predictions on the validation set
predictions = trainer.predict(tokenized_datasets['validation'])

# Extract the predicted labels and true labels
preds = predictions.predictions.argmax(-1)
labels = predictions.label_ids

# Calculate the balanced accuracy
balanced_acc = balanced_accuracy_score(labels, preds)
print("Balanced Accuracy:", balanced_acc)

Map:   0%|          | 0/3374 [00:00<?, ? examples/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ikhlasul.hanif/miniconda3/envs/satdat/lib/python3.9/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/318 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.9704810976982117, 'eval_runtime': 3.6893, 'eval_samples_per_second': 228.767, 'eval_steps_per_second': 7.318, 'epoch': 1.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8307819962501526, 'eval_runtime': 3.769, 'eval_samples_per_second': 223.931, 'eval_steps_per_second': 7.164, 'epoch': 2.0}

  0%|          | 0/27 [00:00<?, ?it/s]

{'eval_loss': 0.8319176435470581, 'eval_runtime': 4.2487, 'eval_samples_per_second': 198.649, 'eval_steps_per_second': 6.355, 'epoch': 3.0}
{'train_runtime': 188.3223, 'train_samples_per_second': 53.748, 'train_steps_per_second': 1.689, 'train_loss': 0.9069303116708431, 'epoch': 3.0}

  0%|          | 0/27 [00:00<?, ?it/s]

Balanced Accuracy: 0.3708772325647581